Repository MRtrix3/mrtrix3, pull requests merged in 2018-11, with the labels that each got.

#1483 mrcalc: added 'pi' as special keyword.
  cmd/mrcalc.cpp
  core/math/math.h
  docs/reference/commands/mrcalc.rst
Labels: enhancement

#1490 mrview Connectome tool: 'transparency' -> 'opacity'
  src/gui/mrview/tool/connectome/connectome.cpp
Labels: gui

#1418 set_path: add -remove option
  set_path
Labels: build, enhancement

#1497 DICOM: increase resilience to errors and empty fields
  core/file/dicom/element.cpp
  core/file/dicom/element.h
  core/file/dicom/image.cpp
  core/file/dicom/series.cpp
Labels: bug

#1503 dwiextract: Fix extraction based on total readout time
  cmd/dwiextract.cpp
Labels: bug

#1427 Appveyor take2
  appveyor.yml
  build
  configure
Labels: Windows

#1504 mrtrix3.image.statistic(): Fix parameter naming
  lib/mrtrix3/_5ttgen/gif.py
  lib/mrtrix3/image.py
  run_pylint
Labels: bug, scripts

#1499 DICOM: be more lenient with slice timing vector in Siemens mosaics
  core/file/dicom/mapper.cpp
Labels: bug
