Repository MRtrix3/mrtrix3, pull requests merged in 2018-07, with the labels that each got.

#1382 Scripts: Tweak message on command failure
  lib/mrtrix3/app.py
Labels: scripts

#1383 Dwipreproc: Handle inappropriate slspec input
  bin/dwipreproc
Labels: scripts

#1385 mrtrix3.file.delTemporary(): Compatibility with list input
  bin/dwipreproc
  lib/mrtrix3/file.py
Labels: scripts

#1384 fixelcfestats: Remove erroneous warning
  cmd/fixelcfestats.cpp
Labels: bug

#1367 MSYS2: fix segfault due to use of %zu printf format
  check_syntax
  core/file/dicom/select_cmdline.cpp
  core/progressbar.cpp
  core/types.h
Labels: Windows, bug

#1410 TravisCI and pylint updates
  .travis.yml
  bin/blend
  bin/dwipreproc
  bin/population_template
  lib/mrtrix3/app.py
  lib/mrtrix3/fsl.py
  lib/mrtrix3/run.py
  testing/pylint.rc
Labels: scripts

#1393 pylint: Test build and configure scripts
  .travis.yml
  bin/blend
  bin/dwipreproc
  bin/population_template
  build
  check_syntax
  configure
  core/file/dicom/select_cmdline.cpp
  core/progressbar.cpp
  core/types.h
  lib/mrtrix3/app.py
  lib/mrtrix3/fsl.py
  lib/mrtrix3/run.py
  run_pylint
  testing/pylint.rc
Labels: build

#1413 app.makeTempDir(): Fix syntax error
  lib/mrtrix3/app.py
Labels: bug, critical, scripts
