Repository MRtrix3/mrtrix3, pull requests merged in 2018-09, with the labels that each got.

#1455 dwi2response: Accept floating-point numbers in -shells option
  bin/dwi2response
Labels: bug, scripts

#1451 amp2response: Bug fix and speedup
  cmd/amp2response.cpp
Labels: bug, enhancement

#1456 tck2connectome empty output on 4-D parcellation image
  cmd/tck2connectome.cpp
  src/connectome/connectome.cpp
Labels: enhancement

#1459 Change FSL autodetect behaviour
  lib/mrtrix3/fsl.py
Labels: scripts
