Repository MRtrix3/mrtrix3, pull requests merged in 2018-04, with the labels that each got.

#1284 OpenGL: Prevent uninitialised variable memory warnings
  src/gui/opengl/gl.h
Labels: bug, gui

#1283 run.function(): Support keyword arguments
  lib/mrtrix3/run.py
Labels: enhancement, scripts

#1277 Scripts: Fix -continue option
  lib/mrtrix3/app.py
  lib/mrtrix3/run.py
Labels: bug, scripts

#1276 Docs to dev
  docs/constrained_spherical_deconvolution/response_function_estimation.rst
Labels: documentation

#1288 tckmap: Fix segfault with -dec -stat_vox mean combination
  src/dwi/tractography/mapping/writer.h
Labels: bug

#1260 warpinit: maintain strides of template image if possible
  cmd/sh2amp.cpp
  cmd/warpinit.cpp
  core/filter/warp.h
Labels: enhancement

#1170 mrview: overlay load
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/overlay.h
Labels: bug, gui

#1115 mrview: removed updateGL() after pan_event.
  src/gui/mrview/mode/base.cpp
  src/gui/mrview/window.cpp
Labels: gui, test wanted

#1290 dwiextract: Add options for exporting gradient table
  cmd/dwiextract.cpp
  docs/reference/commands/dwiextract.rst
Labels: enhancement

#1294 mrview: Add some more command-line options
  docs/reference/commands/mrview.rst
  src/gui/mrview/colourmap_button.cpp
  src/gui/mrview/colourmap_button.h
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/tractography/tractography.cpp
  src/gui/mrview/window.cpp
Labels: enhancement, gui

#1296 run.command(): More robust text decoding
  lib/mrtrix3/run.py
Labels: scripts, test wanted

#1291 Strides option accepts image
  cmd/mrtransform.cpp
  core/stride.cpp
  docs/reference/commands/amp2sh.rst
  docs/reference/commands/dwi2fod.rst
  docs/reference/commands/dwiextract.rst
  docs/reference/commands/maskfilter.rst
  docs/reference/commands/mrconvert.rst
  docs/reference/commands/mrfilter.rst
  docs/reference/commands/mrtransform.rst
  docs/reference/commands/sh2amp.rst
  docs/reference/commands/shconv.rst
Labels: enhancement

#1301 mtnormalise bug fix
  cmd/mtnormalise.cpp
Labels: bug

#1145 Fix mrcat for complex-valued images.
  cmd/mrcat.cpp
  docs/reference/commands/mrcat.rst
Labels: bug, enhancement, test wanted

#1293 Prevent erroneous command-line usage warnings
  cmd/fixelconvert.cpp
  cmd/fixelcorrespondence.cpp
  cmd/fixelreorient.cpp
  cmd/mrcalc.cpp
  cmd/tck2fixel.cpp
  cmd/tckconvert.cpp
  cmd/tckmap.cpp
  cmd/voxel2fixel.cpp
  cmd/warp2metric.cpp
  core/app.cpp
  core/app.h
  core/cmdline_option.h
  core/stride.cpp
  docs/reference/commands/tckedit.rst
  docs/reference/commands/tckgen.rst
  src/dwi/tractography/roi.cpp
  testing/cmd/testing_diff_fixel.cpp
Labels: bug

#1237 run.command(): Support native Windows Python
  lib/mrtrix3/run.py
Labels: Windows, bug, scripts

#1314 tckgen: Fix -backtrack memory error
  src/dwi/tractography/tracking/method.cpp
Labels: bug
