Repository MRtrix3/mrtrix3, pull requests merged in 2018-08, with the labels that each got.

#1409 tckdfc: Fix absence of output with -static option
  cmd/tckdfc.cpp
  src/dwi/tractography/mapping/writer.h
Labels: bug

#1389 Scripts: command_history behaviour
  bin/5ttgen
  bin/dwi2response
  bin/dwibiascorrect
  bin/dwiintensitynorm
  bin/dwipreproc
  bin/labelsgmfix
  bin/population_template
  cmd/mrconvert.cpp
  core/header.cpp
  core/header.h
  core/image.h
  docs/reference/commands/mrconvert.rst
  lib/mrtrix3/_5ttgen/freesurfer.py
  lib/mrtrix3/_5ttgen/fsl.py
  lib/mrtrix3/_5ttgen/gif.py
  lib/mrtrix3/app.py
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/fa.py
  lib/mrtrix3/dwi2response/manual.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
  lib/mrtrix3/run.py
Labels: enhancement, scripts

#1416 mrconvert -vox: Permit single value input
  cmd/mrconvert.cpp
  docs/reference/commands/mrconvert.rst
Labels: enhancement

#1411 docs: update remote display recommendations
  docs/troubleshooting/display_issues.rst
Labels: documentation

#1381 Docs: New page on handling external modules
  docs/index.rst
  docs/installation/windows_install.rst
  docs/tips_and_tricks/external_modules.rst
  set_path
Labels: documentation

#1417 Links to config options take 2
  core/file/dicom/definitions.h
  core/file/dicom/element.cpp
  core/file/utils.h
  core/mrtrix.h
  docs/format_config_options
  docs/quantitative_structural_connectivity/labelconvert_tutorial.rst
  docs/reference/config_file_options.rst
  docs/troubleshooting/display_issues.rst
  docs/troubleshooting/performance_and_crashes.rst
  src/gui/mrview/volume.h
Labels: documentation, enhancement

#1407 Changes to temporary directory handling
  core/file/utils.h
  docs/reference/config_file_options.rst
  lib/mrtrix3/app.py
  lib/mrtrix3/run.py
Labels: enhancement, scripts

#1422 Disable signal handlers with env var
  core/app.cpp
  core/file/config.cpp
  core/file/nifti1_utils.cpp
  core/file/utils.h
  core/math/rng.h
  core/signal_handler.cpp
  core/thread.cpp
  docs/format_config_options
  docs/format_environment_variables
  docs/generate_user_docs.sh
  docs/index.rst
  docs/reference/config_file_options.rst
  docs/reference/environment_variables.rst
  src/gui/opengl/gl_core_3_3.cpp
  src/surface/mesh.cpp
Labels: documentation

#1425 docs: update install instructions, notably for Windows
  appveyor.yml
  docs/installation/linux_install.rst
  docs/installation/mac_install.rst
  docs/installation/windows_install.rst
Labels: build, documentation

#1426 mrconvert update doc
  cmd/mrconvert.cpp
  docs/getting_started/command_line.rst
  docs/reference/commands/mrconvert.rst
Labels: documentation, enhancement

#1435 Silence compiler warnings take3
  .travis.yml
  cmd/amp2response.cpp
  cmd/dwidenoise.cpp
  cmd/mrdegibbs.cpp
  cmd/tensor2metric.cpp
  cmd/transformcalc.cpp
  cmd/transformconvert.cpp
  configure
  core/filter/fft.h
  core/math/ZSH.h
  core/math/average_space.h
  core/math/check_gradient.h
  core/math/least_squares.h
  core/math/sphere.h
  core/math/stats/typedefs.h
  core/math/versor.h
  core/phase_encoding.cpp
  core/phase_encoding.h
  core/silence_eigen_warnings.h
  core/types.h
  src/connectome/connectome.h
  src/dwi/gradient.h
  src/dwi/tractography/GT/gt.h
  src/dwi/tractography/GT/spatiallock.h
  src/dwi/tractography/algorithms/tensor_det.h
  src/dwi/tractography/tracking/early_exit.h
  src/gui/dwi/renderer.h
  src/gui/mrview/tool/connectome/file_data_vector.h
  src/gui/mrview/tool/connectome/matrix_list.h
  src/gui/mrview/tool/screen_capture.cpp
  src/gui/opengl/gl.h
  src/gui/silence_qt_warnings.h
  src/registration/transform/base.h
  src/registration/transform/initialiser_helpers.cpp
  src/registration/transform/initialiser_helpers.h
  src/registration/transform/search.h
  testing/cmd/testing_diff_matrix.cpp
Labels: build, enhancement

#1440 tckgen: Permit -downsample 1
  src/dwi/tractography/tracking/tractography.cpp
Labels: bug

#1430 command_history: Only use quotes when needed
  core/app.cpp
  core/file/path.h
  core/formats/mrtrix_utils.cpp
  core/header.cpp
Labels: enhancement
