Repository MRtrix3/mrtrix3, pull requests merged in 2018-10, with the labels that each got.

#1465 Fix bug json.load() -> json.loads()
  lib/mrtrix3/image.py
Labels: bug, scripts

#1466 Python image header decode
  lib/mrtrix3/image.py
Labels: scripts

#1472 dcminfo: fix -tags output
  cmd/dcminfo.cpp
  core/file/dicom/element.cpp
  core/file/dicom/element.h
Labels: bug, enhancement

#1473 mrview: fix -norealign option
  src/gui/mrview/window.cpp
Labels: bug, gui
