Repository MRtrix3/mrtrix3, pull requests merged in 2018-05, with the labels that each got.

#1319 mrview: Fix a couple of command-line options
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/window.cpp
Labels: bug, gui

#1324 NIfTI: handle near-zero w component in qform
  core/file/nifti1_utils.cpp
  core/file/nifti2_utils.cpp
Labels: bug

#1325 MR::printf(): Use va_copy()
  core/mrtrix.h
Labels: bug, test wanted

#1326 tckstats: Fix for empty track file
  cmd/tckstats.cpp
  src/dwi/tractography/editing/receiver.cpp
Labels: bug

#1320 mrview Connectome tool: Edge visibility by nodes change
  src/dwi/tractography/ACT/gmwmi.cpp
  src/dwi/tractography/ACT/gmwmi.h
  src/gui/mrview/tool/connectome/connectome.cpp
  src/gui/mrview/tool/connectome/connectome.h
  src/gui/mrview/tool/connectome/types.h
Labels: gui

#1323 fix locale handling in GUI applications
  cmd/mrview.cpp
  core/app.cpp
  src/gui/gui.cpp
  src/gui/gui.h
Labels: bug, gui

#1309 Correct documentation of response function estimation
  docs/concepts/global_intensity_normalisation.rst
  docs/constrained_spherical_deconvolution/constrained_spherical_deconvolution.rst
  docs/constrained_spherical_deconvolution/multi_shell_multi_tissue_csd.rst
  docs/constrained_spherical_deconvolution/response_function_estimation.rst
  docs/dwi_preprocessing/denoising.rst
  docs/fixel_based_analysis/common_fba_steps/compute_FC.rst
  docs/fixel_based_analysis/common_fba_steps/tractography.rst
  docs/fixel_based_analysis/displaying_results_with_streamlines.rst
  docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
  docs/fixel_based_analysis/st_fibre_density_cross-section.rst
  docs/index.rst
  docs/quantitative_structural_connectivity/act.rst
  docs/quantitative_structural_connectivity/global_tractography.rst
  docs/quantitative_structural_connectivity/labelconvert_after.png
  docs/quantitative_structural_connectivity/labelconvert_before.png
  docs/quantitative_structural_connectivity/labelconvert_tutorial.rst
  docs/quantitative_structural_connectivity/sift.rst
  docs/reference/references.rst
  docs/reference/scripts/dwi2response.rst
  docs/troubleshooting/FAQ.rst
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
Labels: documentation, enhancement

#1316 mrview: Fix memory error in Lightbox mode
  src/gui/mrview/displayable.h
  src/gui/mrview/gui_image.cpp
  src/gui/mrview/gui_image.h
  src/gui/mrview/mode/base.cpp
  src/gui/mrview/mode/base.h
  src/gui/mrview/mode/lightbox.cpp
  src/gui/mrview/mode/lightbox.h
  src/gui/mrview/mode/volume.cpp
  src/gui/mrview/tool/roi_editor/item.cpp
  src/gui/mrview/volume.h
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
  src/gui/projection.h
Labels: bug, gui

#1327 mrhistmatch: New matching modes
  .travis.yml
  cmd/mrhistmatch.cpp
  docs/reference/commands/mrhistmatch.rst
  docs/reference/commands_list.rst
  testing/tests/mrhistmatch
Labels: enhancement

#1332 changes to ensure consistent version and build date
  .gitignore
  build
  cmd/tckconvert.cpp
  core/app.cpp
  core/app.h
  core/command.h
  src/dwi/tractography/properties.h
  src/exec_version.h
  travis.sh
Labels: build, documentation

#1340 RC3 hot-fixes
  .gitignore
  configure
Labels: bug, critical

#1342 Prevent erroneous command-line usage warning
  core/app.h
Labels: bug

#1343 Documentation fixes / updates after 3.0_RC3 merge
  core/file/utils.h
  docs/getting_started/image_data.rst
  docs/reference/config_file_options.rst
Labels: documentation

#1346 dwi2response: Fix for absent -mask and no gradient table
  bin/dwi2response
Labels: bug, scripts

#1348 build: Only use stderr
  build
  testing/tests/mrhistmatch
Labels: build

#1349 strip() function now also strips null characters
  .gitignore
  bin/dwi2response
  configure
  core/app.h
  core/file/dicom/definitions.h
  core/file/dicom/element.cpp
  core/file/utils.h
  core/mrtrix.h
  docs/getting_started/image_data.rst
  docs/reference/config_file_options.rst
Labels: bug

#1351 FBA docs typo fix
  docs/fixel_based_analysis/common_fba_steps/sift.rst
Labels: bug, documentation

#1353 5ttgen: Fix printing output of 5ttcheck
  bin/5ttgen
Labels: bug, scripts

#1355 Fba docs finalfixes
  docs/fixel_based_analysis/common_fba_steps/statistics.rst
  docs/fixel_based_analysis/st_fibre_density_cross-section.rst
Labels: bug, documentation
