Repository MRtrix3/mrtrix3, pull requests merged in 2018-03, with the labels that each got.

#1264 Stats: Fix segfault when using -nonstationary
  cmd/connectomestats.cpp
  cmd/fixelcfestats.cpp
  cmd/mrclusterstats.cpp
Labels: bug

#1271 Fix parsing of -strides option
  core/stride.cpp
Labels: bug, critical

#1272 Docs to dev
  docs/fixel_based_analysis/common_fba_steps/compute_AFD.rst
  docs/fixel_based_analysis/common_fba_steps/compute_FC.rst
  docs/fixel_based_analysis/common_fba_steps/fixelcorrespondence.rst
  docs/fixel_based_analysis/common_fba_steps/population_template.rst
  docs/fixel_based_analysis/common_fba_steps/population_template2.rst
  docs/fixel_based_analysis/common_fba_steps/template_mask.rst
  docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
  docs/fixel_based_analysis/st_fibre_density_cross-section.rst
Labels: documentation

#1259 Permit writing of empty tracks to file
  src/dwi/tractography/SIFT/model.h
  src/dwi/tractography/SIFT/sifter.cpp
  src/dwi/tractography/connectome/extract.cpp
  src/dwi/tractography/file.h
  src/dwi/tractography/file_base.h
  src/dwi/tractography/resampling/fixed_num_points.cpp
  src/dwi/tractography/scalar_file.h
  src/dwi/tractography/tracking/write_kernel.cpp
Labels: enhancement

#1267 configure: Alter debug optimisation on Windows
  configure
Labels: Windows, build

#1214 fixel2tsf NaN fix
  cmd/fixel2tsf.cpp
  cmd/tsfvalidate.cpp
  docs/reference/commands/tsfvalidate.rst
  docs/reference/commands_list.rst
  src/gui/mrview/tool/tractography/tractogram.cpp
  src/gui/mrview/tool/tractography/tractogram.h
Labels: bug, question

#1185 tckstats: New option -explicit
  cmd/tckstats.cpp
  docs/reference/commands/tckstats.rst
Labels: enhancement, question
