Repository MRtrix3/mrtrix3, pull requests merged in 2019-08, with the labels that each got.

#1665 linear transformation from sets of scanner coordinates
  cmd/transformcalc.cpp
  docs/reference/commands/transformcalc.rst
  src/gui/mrview/tool/view.cpp
Labels: bug

#1672 dwicat: Fix for updated Python API
  bin/dwicat
Labels: bug, scripts

#1675 Fixes to mrtrix3.matrix module
  lib/mrtrix3/matrix.py
Labels: bug, scripts

#1677 connectome2tck: Prevent valgrind error
  src/dwi/tractography/connectome/extract.h
Labels: bug

#1670 dwifslpreproc
  bin/dwifslpreproc
  cmd/mrdegibbs.cpp
  docs/concepts/pe_scheme.rst
  docs/dwi_preprocessing/dwifslpreproc.rst
  docs/fixel_based_analysis/common_fba_steps/dwifslpreproc.rst
  docs/fixel_based_analysis/common_fba_steps/dwipreproc.rst
  docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
  docs/fixel_based_analysis/st_fibre_density_cross-section.rst
  docs/getting_started/beginner_dwi_tutorial.rst
  docs/index.rst
  docs/quantitative_structural_connectivity/act.rst
  docs/reference/commands/dwifslpreproc.rst
  docs/reference/commands/mrdegibbs.rst
  docs/reference/commands_list.rst
Labels: scripts

#1653 GitHub Issue / PR templates and contributing guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/general.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#1622 Documentation to Discourse wiki
  docs/README.md
  docs/conf.py
  docs/fixel_based_analysis/common_fba_steps/statistics.rst
  docs/index.rst
  docs/installation/hpc_clusters_install.rst
  docs/installation/linux_install.rst
  docs/spatial_normalisation/warping_images_with_warps_from_other_packages.rst
  docs/tips_and_tricks/troubleshooting.rst
  docs/troubleshooting/FAQ.rst
  docs/troubleshooting/advanced_debugging.rst
  docs/troubleshooting/display_issues.rst
  docs/troubleshooting/performance_and_crashes.rst
Labels: documentation, question

#1659 mrcalc: Updates to complex data handling
  cmd/mrcalc.cpp
  docs/reference/commands/mrcalc.rst
Labels: enhancement

#1679 Fix two buffer overruns
  core/adapter/replicate.h
  core/image.h
Labels: bug

#1680 docs: fix math typesetting again
  docs/dwi_preprocessing/denoising.rst
Labels: documentation

#1682 Smarter default patch size for denoising
  cmd/dwidenoise.cpp
  docs/reference/commands/dwidenoise.rst
Labels: enhancement

#1686 foreach: Use threading rather than multiprocessing module
  bin/foreach
Labels: bug, scripts

#1687 dwi2response msmt_5tt: Fix erroneous warning
  lib/mrtrix3/dwi2response/msmt_5tt.py
Labels: bug, scripts

#1688 Script updates for recent PRs
  cmd/mrthreshold.cpp
  lib/mrtrix3/_5ttgen/freesurfer.py
  lib/mrtrix3/_5ttgen/fsl.py
  lib/mrtrix3/_5ttgen/gif.py
  lib/mrtrix3/dwi2response/tournier.py
Labels: bug, scripts

#1691 Force copy of pe_scheme rows instead of proxy
  core/file/json_utils.cpp
Labels: bug

#1694 configure: fix Python decode error on Windows
  configure
Labels: Windows, bug, build

#1695 Updates for compatibility with #1603
  cmd/connectome2tck.cpp
  src/dwi/tractography/connectome/matrix.cpp
  src/dwi/tractography/file.h
Labels: bug, critical

#1696 build: fix Python decode error on Windows
  build
Labels: Windows, bug, build

#1698 set_path: fix Python decode error on Windows
  set_path
Labels: Windows, bug

#1649 mrview: overlay n dimensional data
  src/gui/dialog/progress.cpp
  src/gui/dwi/render_frame.cpp
  src/gui/dwi/renderer.cpp
  src/gui/dwi/renderer.h
  src/gui/gui.cpp
  src/gui/gui.h
  src/gui/mrview/gui_image.cpp
  src/gui/mrview/mode/base.cpp
  src/gui/mrview/mode/base.h
  src/gui/mrview/mode/lightbox.cpp
  src/gui/mrview/mode/ortho.cpp
  src/gui/mrview/mode/slice.cpp
  src/gui/mrview/mode/volume.cpp
  src/gui/mrview/tool/connectome/connectome.cpp
  src/gui/mrview/tool/connectome/edge.cpp
  src/gui/mrview/tool/connectome/node.cpp
  src/gui/mrview/tool/connectome/shaders.cpp
  src/gui/mrview/tool/connectome/shaders.h
  src/gui/mrview/tool/fixel/base_fixel.cpp
  src/gui/mrview/tool/fixel/fixel.cpp
  src/gui/mrview/tool/odf/odf.cpp
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/overlay.h
  src/gui/mrview/tool/roi_editor/item.cpp
  src/gui/mrview/tool/roi_editor/model.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/roi_editor/undoentry.cpp
  src/gui/mrview/tool/tractography/tractogram.cpp
  src/gui/mrview/tool/tractography/tractography.cpp
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/volume.cpp
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
  src/gui/opengl/gl.cpp
  src/gui/opengl/gl.h
  src/gui/shview/render_window.cpp
Labels: gui
