Repository MRtrix3/mrtrix3, pull requests merged in 2019-11, with the labels that each got.

#1791 dwifslpreproc: Add EddyQC reference
  bin/dwifslpreproc
  docs/reference/commands/dwifslpreproc.rst
Labels: documentation, scripts

#1792 matrix.save_transform(): Boost precision
  lib/mrtrix3/matrix.py
Labels: scripts

#1796 Change testing log filenames
  appveyor.yml
  run_tests
  travis.sh
Labels: CI

#1801 TravisCI: Explicit brew update call
  .travis.yml
Labels: CI

#1802 generate_user_docs.sh macOS compatible
  docs/generate_user_docs.sh
Labels: MacOSX, documentation

#1795 configure: also remove miniconda from path
  configure
Labels: build

#1807 RNG: use std::random_device to initialise on all platforms
  core/math/rng.h
Labels: enhancement

#1794 New MR::to<std::complex>() specialisation
  cmd/mrcalc.cpp
  core/file/json_utils.cpp
  core/mrtrix.h
  src/connectome/lut.cpp
  testing/cmd/testing_diff_matrix.cpp
  testing/cmd/testing_to.cpp
  testing/tests/to
Labels: bug, enhancement

#1793 tcksift: Sorter fix for rare usage
  src/dwi/tractography/SIFT/gradient_sort.cpp
  src/dwi/tractography/SIFT/gradient_sort.h
  src/dwi/tractography/SIFT/sifter.cpp
Labels: bug

#1800 dirorder: Exhaustive search
  cmd/dirflip.cpp
  cmd/dirorder.cpp
  cmd/dirsplit.cpp
  docs/reference/commands/dirflip.rst
  docs/reference/commands/dirsplit.rst
Labels: enhancement

#1809 Mrview: insert images after current
  src/gui/mrview/window.cpp
Labels: enhancement, gui

#1751 core/app: fix abbreviated option parsing
  core/app.cpp
Labels: bug

#1810 configure: update flags for static linking
  configure
Labels: build

#1720 MRView tractogram tool: fix bug in lines render when thresholding
  src/gui/mrview/tool/tractography/tractogram.cpp
Labels: bug, gui

#1707 Progressbar restrict construction to main thread
  core/app.cpp
  core/app.h
  core/progressbar.h
Labels: enhancement

#1814 tckgen: fix out-of-bounds access in downsampler
  src/dwi/tractography/resampling/downsampler.cpp
Labels: bug

#1818 Testing: Change fod2fixel temp data paths
  run_tests
  testing/binaries/tests/fod2fixel
Labels: CI

#1817 tckgen: fix out-of-bounds access in downsampler
  src/dwi/tractography/resampling/downsampler.cpp
Labels: bug

#1823 MR::to<>(): Strip whitespace (DICOM fix)
  core/mrtrix.h
  testing/cmd/testing_to.cpp
Labels: bug

#1822 dirflip and dirsplit: Fix command-line option parsing
  cmd/dirflip.cpp
  cmd/dirsplit.cpp
Labels: bug
