Repository MRtrix3/mrtrix3, pull requests merged in 2019-10, with the labels that each got.

#1750 docs: fixed SH description URL
  core/math/SH.cpp
  docs/reference/commands/amp2sh.rst
  docs/reference/commands/dwi2fod.rst
  docs/reference/commands/fixel2sh.rst
  docs/reference/commands/sh2amp.rst
  docs/reference/commands/sh2peaks.rst
  docs/reference/commands/sh2power.rst
  docs/reference/commands/sh2response.rst
  docs/reference/commands/shbasis.rst
  docs/reference/commands/shconv.rst
Labels: documentation

#1738 JSON handling changes
  cmd/mrinfo.cpp
  core/file/json_utils.cpp
  core/file/json_utils.h
Labels: enhancement

#1737 Python: Use of kwargs for API functions
  bin/dwibiascorrect
  bin/dwifslpreproc
  lib/mrtrix3/image.py
  lib/mrtrix3/path.py
Labels: scripts

#1550 Build remove outdated bin
  build
Labels: build, question

#1761 dwifslpreproc: Add help description RE: CUDA
  bin/dwifslpreproc
  docs/reference/commands/dwifslpreproc.rst
Labels: documentation, scripts

#1754 MRView: report 3D texture size
  src/gui/dialog/opengl.cpp
Labels: gui

#1703 Progressbar fix quiet
  core/progressbar.cpp
  core/progressbar.h
  src/gui/dialog/progress.cpp
Labels: bug

#1733 dwipreproc: Fix for rare usage
  bin/dwipreproc
Labels: bug, scripts

#1723 JSON export: Fix PE scheme
  core/file/json_utils.cpp
Labels: bug

#1770 app.py: progress bar: cast to int
  lib/mrtrix3/app.py
Labels: bug

#1776 Fix pylint testing for TravisCI
  bin/5ttgen
  bin/dwi2response
  bin/dwibiascorrect
  bin/dwicat
  bin/dwifslpreproc
  bin/dwigradcheck
  bin/dwinormalise
  bin/dwishellmath
  bin/foreach
  bin/labelsgmfix
  bin/population_template
  bin/responsemean
  lib/mrtrix3/__init__.py
  lib/mrtrix3/algorithm.py
  lib/mrtrix3/app.py
  lib/mrtrix3/fsl.py
  lib/mrtrix3/image.py
  lib/mrtrix3/path.py
  lib/mrtrix3/phaseencoding.py
  lib/mrtrix3/run.py
  lib/mrtrix3/utils.py
  testing/pylint.rc
Labels: CI, scripts

#1765 mrtransform export grad
  cmd/mrtransform.cpp
  docs/reference/commands/mrtransform.rst
Labels: enhancement

#1775 dwifslpreproc: eddy "slspec" export fix
  bin/dwifslpreproc
  lib/mrtrix3/matrix.py
Labels: bug, scripts

#1779 mrconvert -json_import: Preserve existing key-values
  core/file/json_utils.cpp
  core/file/json_utils.h
Labels: bug

#1764 mrdegibbs: fix check for number of entries supplied to -axes
  cmd/mrdegibbs.cpp
Labels: bug

#1783 matrix.save_numeric(): Improve header/footer formatting
  lib/mrtrix3/matrix.py
Labels: bug, scripts

#1766 mtnormalise: alternative implementation
  cmd/mtnormalise.cpp
  docs/reference/commands/mtnormalise.rst
Labels: enhancement

#1778 connectome2tck: Skip non-valid exemplars
  cmd/connectome2tck.cpp
  src/dwi/tractography/connectome/exemplar.cpp
  src/dwi/tractography/connectome/exemplar.h
  src/dwi/tractography/connectome/extract.cpp
Labels: bug
