Repository MRtrix3/mrtrix3, pull requests merged in 2019-02, with the labels that each got.

#1545 Update dwi2response dhollander
  bin/dwi2response
  docs/constrained_spherical_deconvolution/response_function_estimation.rst
  docs/reference/scripts/dwi2response.rst
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/tournier.py
Labels: enhancement, scripts

#1554 Prevent deep multi-threading
  core/algo/random_threaded_loop.h
  core/algo/stochastic_threaded_loop.h
  core/algo/threaded_loop.h
  core/thread.cpp
  core/thread.h
  core/thread_queue.h
Labels: enhancement

#1556 Prevent duplicated ROI entries in track files
  cmd/tckedit.cpp
  cmd/tckinfo.cpp
  cmd/tsfinfo.cpp
  src/dwi/tractography/file_base.cpp
  src/dwi/tractography/file_base.h
  src/dwi/tractography/properties.cpp
  src/dwi/tractography/properties.h
  src/dwi/tractography/tracking/tractography.cpp
Labels: bug
