Repository MRtrix3/mrtrix3, pull requests merged in 2019-04, with the labels that each got.

#1560 mrcat: Fix segfault on single-voxel images
  cmd/mrcat.cpp
Labels: bug

#1563 progressbar: disable line wrapping while updating terminal
  .travis.yml
  core/progressbar.cpp
Labels: enhancement

#1570 BitSet::resize(): Bug fix
  core/bitset.cpp
Labels: bug

#1582 connectome2tck: Fix assertion failure / segfault
  cmd/connectome2tck.cpp
Labels: bug

#1568 mrview: Report interpolation of printed values
  src/gui/mrview/mode/base.cpp
  src/gui/mrview/tool/overlay.cpp
Labels: gui

#1562 Docs: Tweak tck description and add tsf
  docs/getting_started/image_data.rst
Labels: documentation

#1561 warpcorrect: added option to specify out of bounds value or vector
  cmd/warpcorrect.cpp
  docs/reference/commands/warpcorrect.rst
  docs/reference/commands_list.rst
Labels: enhancement

#1557 population_template: fix -continue
  bin/population_template
Labels: bug, scripts

#1555 4D schemes preserve on [] notation
  cmd/mrcalc.cpp
  cmd/mrcat.cpp
  cmd/mrmath.cpp
  core/dwi/gradient.cpp
  core/dwi/gradient.h
  core/header.cpp
  core/header.h
Labels: enhancement

#1572 mrview Tractography tool: Fix assertion on TSF load
  src/gui/mrview/tool/tractography/tractogram.cpp
Labels: bug, gui

#1531 DICOM: Variable parameters
  core/file/dicom/mapper.cpp
Labels: enhancement

#1574 mrview Lightbox: Don't modify GL elements in wrong context
  src/gui/mrview/mode/lightbox.cpp
  src/gui/mrview/mode/lightbox.h
Labels: bug, gui

#1595 Prevent new compiler warnings on Clang8
  core/header.h
  core/image_io/default.h
  core/transform.h
Labels: build

#1590 Update python signal handling
  bin/foreach
  lib/mrtrix3/app.py
  lib/mrtrix3/run.py
Labels: Windows, scripts, test wanted

#1597 Python help: Example usage fix
  lib/mrtrix3/app.py
Labels: bug, scripts

#1526 re-formulate and multi-thread amp2response
  cmd/amp2response.cpp
  core/math/constrained_least_squares.h
  docs/reference/commands/amp2response.rst
Labels: enhancement

#1599 amp2sh: allow cartesian directions
  cmd/amp2sh.cpp
  core/header.h
  core/image_io/default.h
  core/image_io/variable_scaling.h
  core/transform.h
  docs/reference/commands/amp2sh.rst
Labels: enhancement

#1606 app.Parser.add_citation(): Change syntax
  bin/5ttgen
  bin/dwigradcheck
  bin/dwipreproc
  bin/labelsgmfix
  lib/mrtrix3/_5ttgen/fsl.py
  lib/mrtrix3/app.py
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/fa.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
  lib/mrtrix3/dwibiascorrect/ants.py
  lib/mrtrix3/dwibiascorrect/fsl.py
Labels: scripts

#1610 dwidenoise: fix up issues with spacing in copyright notice
  cmd/dwidenoise.cpp
  docs/reference/commands/dwidenoise.rst
Labels: documentation
