Repository MRtrix3/mrtrix3, pull requests merged in 2019-07, with the labels that each got.

#1613 python: simple addition to simplify importing MRtrix3 libraries
  .gitignore
  bin/5ttgen
  bin/dwi2response
  bin/dwibiascorrect
  bin/dwicat
  bin/dwigradcheck
  bin/dwinormalise
  bin/dwipreproc
  bin/dwishellmath
  bin/foreach
  bin/labelsgmfix
  bin/mrtrix3.py
  bin/population_template
  bin/responsemean
  docs/generate_user_docs.sh
  docs/tips_and_tricks/external_modules.rst
  docs/troubleshooting/FAQ.rst
  lib/mrtrix3/_5ttgen/fsl.py
  lib/mrtrix3/__init__.py
  lib/mrtrix3/app.py
  lib/mrtrix3/dwibiascorrect/fsl.py
  lib/mrtrix3/path.py
  lib/mrtrix3/run.py
  lib/mrtrix3/utils.py
  run_pylint
Labels: enhancement, question, scripts

#1637 mrmetric: fix cross correlation metric looping
  cmd/mrmetric.cpp
  docs/reference/commands/mrmetric.rst
  src/gui/opengl/font.cpp
  src/gui/projection.h
  src/registration/metric/thread_kernel.h
Labels: bug

#1642 mrview: fix bug introduced in #1638
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/tool/view.h
Labels: bug, gui

#1648 dwigradcheck: Fix -force option
  bin/dwigradcheck
Labels: bug, scripts

#1507 Precise quantification of streamlines lengths
  cmd/tckgen.cpp
  cmd/tckresample.cpp
  cmd/tckstats.cpp
  docs/reference/commands/tckgen.rst
  docs/reference/commands/tckresample.rst
  docs/reference/commands/tckstats.rst
  docs/reference/commands_list.rst
  src/dwi/tractography/algorithms/calibrator.h
  src/dwi/tractography/algorithms/fact.h
  src/dwi/tractography/algorithms/iFOD1.h
  src/dwi/tractography/algorithms/iFOD2.h
  src/dwi/tractography/algorithms/nulldist.h
  src/dwi/tractography/algorithms/sd_stream.h
  src/dwi/tractography/algorithms/seedtest.h
  src/dwi/tractography/algorithms/tensor_det.h
  src/dwi/tractography/connectome/metric.h
  src/dwi/tractography/editing/worker.cpp
  src/dwi/tractography/mapping/mapper.cpp
  src/dwi/tractography/streamline.h
  src/dwi/tractography/tracking/exec.h
  src/dwi/tractography/tracking/generated_track.h
  src/dwi/tractography/tracking/shared.cpp
  src/dwi/tractography/tracking/shared.h
  src/dwi/tractography/tracking/tractography.cpp
  src/dwi/tractography/tracking/types.h
Labels: enhancement

#1646 Allow command inputs to be overwritten safely
  core/file/utils.h
Labels: enhancement

#1660 Header::concatenate(): Catch segfault
  core/header.cpp
Labels: bug
