Repository MRtrix3/mrtrix3, pull requests merged in 2019-09, with the labels that each got.

#1705 Mrview fix dixel odf render
  src/gui/dwi/renderer.cpp
Labels: bug, gui

#1706 warpcorrect nan
  cmd/warpcorrect.cpp
Labels: bug

#1715 Fix sh precomputer again
  core/math/SH.h
  testing/cmd/testing_sh_precomputer.cpp
  testing/tests/sh_precomputer
Labels: bug, critical

#1714 dwi2mask: Fix segfault with -fslgrad
  src/dwi/gradient.cpp
Labels: bug

#1717 Python script backend: fix handling of -nthreads
  lib/mrtrix3/app.py
Labels: bug, scripts

#1711 foreach fixes
  bin/foreach
  docs/reference/commands/foreach.rst
Labels: bug, scripts

#1635 SH description: Revise
  cmd/fixel2sh.cpp
  cmd/sh2amp.cpp
  cmd/sh2peaks.cpp
  cmd/sh2power.cpp
  cmd/sh2response.cpp
  cmd/shbasis.cpp
  cmd/shconv.cpp
  core/math/SH.cpp
  docs/concepts/orthonormal_sh_basis.rst
  docs/concepts/sh_basis_lmax.rst
  docs/concepts/spherical_harmonics.rst
  docs/index.rst
  docs/reference/commands/amp2sh.rst
  docs/reference/commands/dwi2fod.rst
  docs/reference/commands/fixel2sh.rst
  docs/reference/commands/sh2amp.rst
  docs/reference/commands/sh2peaks.rst
  docs/reference/commands/sh2power.rst
  docs/reference/commands/sh2response.rst
  docs/reference/commands/shbasis.rst
  docs/reference/commands/shconv.rst
Labels: documentation

#1722 HCPMMP1 LUT fix
  share/mrtrix3/labelconvert/hcpmmp1_ordered.txt
  share/mrtrix3/labelconvert/hcpmmp1_original.txt
Labels: bug

#1728 tckinfo: fix issue of printing max angle
  src/dwi/tractography/tracking/shared.cpp
Labels: bug

#1726 Installation: Remove numpy dependence
  docs/installation/linux_install.rst
Labels: documentation

#1727 Docs: Install: Add libpng
  docs/installation/linux_install.rst
  docs/installation/mac_install.rst
  docs/installation/windows_install.rst
Labels: documentation
