Repository MRtrix3/mrtrix3, pull requests merged in 2019-12, with the labels that each got.

#1824 GitHub Actions for CI and deployment
  .github/workflows/checks.yml
  .github/workflows/package-linux-anaconda.yml
  .github/workflows/package-macos-anaconda.yml
  .github/workflows/package-windows-msys2.yml
  .travis.yml
  README.md
  appveyor.yml
  build
  configure
  core/file/png.cpp
  core/version.h
  docs/conf.py
  docs/generate_user_docs.sh
  docs/reference/commands/amp2sh.rst
  docs/reference/commands/dwi2fod.rst
  docs/reference/commands/fixel2sh.rst
  docs/reference/commands/sh2amp.rst
  docs/reference/commands/sh2peaks.rst
  docs/reference/commands/sh2power.rst
  docs/reference/commands/sh2response.rst
  docs/reference/commands/shbasis.rst
  docs/reference/commands/shconv.rst
  docs/reference/commands_list.rst
  testing/cmd/testing_diff_matrix.cpp
  testing/cmd/testing_unit_tests_shuffle.cpp
  travis.sh
Labels: CI, enhancement

#1782 dwi2mask: Fix for cleaning filter with cropped data
  cmd/dwi2mask.cpp
Labels: bug

#1812 mrview fixel plot enhancements
  core/image_io/default.h
  docs/reference/config_file_options.rst
  src/gui/mrview/tool/connectome/connectome.cpp
  src/gui/mrview/tool/connectome/edge.cpp
  src/gui/mrview/tool/fixel/base_fixel.cpp
  src/gui/mrview/tool/fixel/base_fixel.h
  src/gui/mrview/tool/fixel/fixel.cpp
  src/gui/mrview/tool/fixel/fixel.h
  src/gui/mrview/tool/fixel/image4D.cpp
  src/gui/mrview/tool/fixel/image4D.h
  src/gui/mrview/tool/fixel/vector_structs.h
  src/gui/mrview/tool/roi_editor/item.cpp
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
Labels: enhancement, gui

#1757 dwipreproc: Fix -eddyqc_all for FSL6
  bin/dwipreproc
Labels: bug, scripts

#1829 CI: Print pylint.log on failure
  .github/workflows/checks.yml
Labels: CI

#1827 Build: Detect outdated configuration
  build
Labels: build

#1828 run.command(): Use same Python interpreter
  lib/mrtrix3/run.py
Labels: scripts

#1752 label2mesh: Skip absent parcels
  cmd/label2mesh.cpp
  core/adapter/subset.h
Labels: bug

#1736 dwipreproc: Permit rigid-body between DWI and SE-EPI
  bin/dwipreproc
  lib/mrtrix3/image.py
Labels: enhancement, scripts

#1837 mrtrix3.app.ProgressBar: Fix line wrapping on construction
  lib/mrtrix3/app.py
Labels: bug, scripts

#1838 app.execute() Fix erroneous error message
  lib/mrtrix3/app.py
Labels: bug, scripts

#1740 mrclusterstats: Make sure template mask is 3D
  cmd/mrclusterstats.cpp
Labels: bug

#1835 SIFT: Fix TDI SH image output
  src/dwi/tractography/SIFT/output.h
Labels: bug

#1850 mrview: fix -overlay.intensity
  src/gui/mrview/adjust_button.h
Labels: bug, gui, test wanted

#1852 mrcolour: Clamp input values
  cmd/mrcolour.cpp
Labels: bug

#1856 update instructions for pushing out version changes
  core/version.h
Labels: documentation, enhancement

#1853 run.command(): Fix mrconvert_keyval usage
  bin/dwishellmath
  bin/labelsgmfix
  bin/population_template
  lib/mrtrix3/_5ttgen/freesurfer.py
  lib/mrtrix3/_5ttgen/fsl.py
  lib/mrtrix3/_5ttgen/gif.py
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/fa.py
  lib/mrtrix3/dwi2response/manual.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
  lib/mrtrix3/dwibiascorrect/ants.py
  lib/mrtrix3/dwibiascorrect/fsl.py
  lib/mrtrix3/dwinormalise/group.py
  lib/mrtrix3/dwinormalise/individual.py
  lib/mrtrix3/run.py
Labels: bug, scripts

#1857 configure: add -conda flag
  configure
Labels: build

#1844 mrview/mrcolour: split off colourmap code from GUI code
  cmd/mrcolour.cpp
  docs/reference/config_file_options.rst
  src/colourmap.cpp
  src/colourmap.h
  src/gui/mrview/colourbars.cpp
  src/gui/mrview/colourbars.h
  src/gui/mrview/colourmap.cpp
  src/gui/mrview/colourmap.h
  src/gui/mrview/colourmap_button.cpp
  src/gui/mrview/colourmap_button.h
  src/gui/mrview/colourmap_menu.cpp
  src/gui/mrview/colourmap_menu.h
  src/gui/mrview/displayable.h
  src/gui/mrview/mode/base.cpp
  src/gui/mrview/tool/connectome/connectome.cpp
  src/gui/mrview/tool/connectome/connectome.h
  src/gui/mrview/tool/fixel/fixel.cpp
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/tractography/track_scalar_file.cpp
  src/gui/mrview/tool/tractography/tractogram.h
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
Labels: build, enhancement, gui

#1859 GitHub: Fix for Windows workflows
  .github/workflows/checks.yml
  .github/workflows/package-windows-msys2.yml
Labels: CI

#1605 New script: mrtrix_cleanup
  bin/mrtrix_cleanup
  docs/reference/commands/mrtrix_cleanup.rst
  docs/reference/commands_list.rst
  lib/mrtrix3/app.py
  lib/mrtrix3/path.py
Labels: scripts

#1862 Fix unused variable compiler warning
  src/gui/lighting_dock.cpp
Labels: CI
