Repository MRtrix3/mrtrix3, pull requests merged in 2020-10, with the labels that each got.

#2187 labelconvert: Error if -spine used but absent from LUT
  cmd/labelconvert.cpp
Labels: bug

#2152 vectorstats: Permit numerical matrix data as input
  cmd/vectorstats.cpp
  core/math/stats/import.h
Labels: enhancement

#2201 Docs: afdconnectivity: Link to preprint
  docs/concepts/afd_connectivity.rst
Labels: documentation

#2211 GitHub workflow: fix homebrew setup in macOS checks
  .github/workflows/checks.yml
Labels: CI/tests, critical

#2208 mrcalc: -modulo operand
  cmd/mrcalc.cpp
  docs/reference/commands/mrcalc.rst
Labels: enhancement

#2216 MGH/MGZ: Fix Colortable V2 write
  core/file/mgh.h
Labels: bug
