Repository MRtrix3/mrtrix3, pull requests merged in 2020-11, with the labels that each got.

#2222 dwidenoise: Avoid memory reallocation
  cmd/dwidenoise.cpp
Labels: question

#2214 tckmap: Revise help page
  cmd/tckmap.cpp
  docs/reference/commands/tckmap.rst
  docs/reference/commands_list.rst
Labels: documentation

#2225 for_each: Tweak error message
  bin/for_each
Labels: scripts

#2157 Enforce Qt5
  configure
  src/gui/dialog/opengl.cpp
  src/gui/dwi/render_frame.cpp
  src/gui/mrview/mode/volume.cpp
  src/gui/mrview/tool/connectome/node_list.cpp
  src/gui/mrview/window.cpp
  src/gui/opengl/font.cpp
  src/gui/opengl/gl.cpp
  src/gui/opengl/gl.h
  src/gui/projection.h
Labels: build, gui

#2194 Docs: DW handling: Describe shells
  .github/workflows/checks.yml
  docs/concepts/dw_scheme.rst
  docs/getting_started/config.rst
  docs/quantitative_structural_connectivity/connectome_tool.rst
Labels: documentation

#2131 Allow NULL image to be specified as output image
  .github/workflows/checks.yml
  cmd/labelconvert.cpp
  core/file/mgh.h
  core/formats/list.cpp
  core/formats/list.h
  core/formats/pipe.cpp
  core/formats/ram.cpp
  core/image_io/ram.cpp
  docs/concepts/afd_connectivity.rst
  docs/concepts/dw_scheme.rst
  docs/getting_started/config.rst
  docs/quantitative_structural_connectivity/connectome_tool.rst
Labels: enhancement

#2155 mrview: add -orientation cmdline option
  docs/reference/commands/mrview.rst
  src/gui/mrview/window.cpp
Labels: enhancement, gui

#2130 dirmerge: don't output a 5th column if single subset
  cmd/dirmerge.cpp
Labels: enhancement

#2204 Pylint fixes for master
  bin/population_template
  testing/pylint.rc
Labels: CI/tests, scripts

#2229 dwifslpreproc: Fix for rare usage
  bin/dwifslpreproc
Labels: bug, scripts

#2236 dwifslpreproc: fix help for -align_seepi option
  bin/dwifslpreproc
  docs/reference/commands/dwifslpreproc.rst
Labels: documentation
