Repository MRtrix3/mrtrix3, pull requests merged in 2020-04, with the labels that each got.

#1996 DICOM import & dcminfo: Enhancements
  cmd/dcminfo.cpp
  core/file/dicom/csa_entry.h
  core/file/dicom/image.cpp
  core/file/dicom/image.h
  core/file/dicom/mapper.cpp
  core/file/dicom/quick_scan.cpp
  core/file/dicom/quick_scan.h
  core/phase_encoding.cpp
  core/phase_encoding.h
  docs/reference/commands/dcminfo.rst
Labels: enhancement

#2012 DICOM selector quit aborts cleanly
  cmd/mrinfo.cpp
  core/exception.h
  core/file/dicom/select_cmdline.cpp
  core/header.cpp
  src/gui/dialog/dicom.cpp
  src/gui/mrview/window.cpp
Labels: enhancement

#2013 mrconvert: Avoid unnecessary warning
  cmd/mrconvert.cpp
Labels: bug

#2017 write_mrtrix.m: fix handling of .mih outputs
  matlab/read_mrtrix.m
  matlab/write_mrtrix.m
Labels: bug

#2028 Minor fixes
  cmd/tckconvert.cpp
  cmd/tcksample.cpp
  core/file/dicom/select_cmdline.cpp
  core/formats/mrtrix_utils.h
  src/dwi/tractography/file_base.h
  src/surface/algo/mesh2image.cpp
Labels: build

#2030 dw_scheme: Fix command-line import
  core/dwi/gradient.cpp
Labels: bug

#2029 dwifslpreproc: support user-provided mask for eddy
  bin/dwifslpreproc
  docs/reference/commands/dwifslpreproc.rst
Labels: enhancement, scripts

#1993 warpfull: enforce header can store linear trafos
  cmd/mrregister.cpp
  cmd/mrtransform.cpp
  cmd/warpconvert.cpp
  core/file/dicom/mapper.cpp
  core/file/nifti_utils.cpp
  core/file/nifti_utils.h
  core/file/path.h
  core/formats/mri.cpp
  src/registration/nonlinear.cpp
Labels: CI

#1985 docs update for release
  README.md
  cmd/fixelconvert.cpp
  cmd/mrinfo.cpp
  cmd/tckconvert.cpp
  cmd/warpinit.cpp
  docs/_static/css/custom.css
  docs/concepts/dw_scheme.rst
  docs/concepts/fixels_dixels.rst
  docs/concepts/pe_scheme.rst
  docs/fixel_based_analysis/mitigating_brain_cropping.rst
  docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
  docs/fixel_based_analysis/st_fibre_density_cross-section.rst
  docs/getting_started/commands.rst
  docs/getting_started/image_data.rst
  docs/getting_started/key_features.rst
  docs/index.rst
  docs/installation/before_install.rst
  docs/installation/build_from_source.rst
  docs/installation/download_mrtrix.png
  docs/installation/hpc_clusters_install.rst
  docs/installation/linux_install.rst
  docs/installation/mac_install.rst
  docs/installation/package_install.rst
  docs/installation/windows_install.rst
  docs/reference/commands/fixelconvert.rst
  docs/reference/commands/tckconvert.rst
  docs/reference/commands/warpinit.rst
  docs/reference/references.rst
  docs/tips_and_tricks/batch_processing_with_foreach.rst
  docs/tips_and_tricks/dicom_handling.rst
Labels: documentation

#2031 Reference fixes for website publication crawler
  cmd/dwi2mask.cpp
  cmd/dwi2tensor.cpp
  cmd/fixelcfestats.cpp
  cmd/fod2dec.cpp
  cmd/fod2fixel.cpp
  cmd/mrtransform.cpp
  cmd/mtnormalise.cpp
  cmd/warp2metric.cpp
  docs/reference/commands/dwi2mask.rst
  docs/reference/commands/dwi2tensor.rst
  docs/reference/commands/fixelcfestats.rst
  docs/reference/commands/fod2dec.rst
  docs/reference/commands/fod2fixel.rst
  docs/reference/commands/mrtransform.rst
  docs/reference/commands/warp2metric.rst
Labels: documentation

#2032 GitHub Actions: don't trigger on pull request edited
  .github/workflows/checks.yml
Labels: CI

#2033 Pre-release hotfixes
  docs/reference/commands/5ttgen.rst
  lib/mrtrix3/_5ttgen/hsvs.py
  testing/binaries/tests/mrconvert
  testing/scripts/tests/dwishellmath
  testing/scripts/tests/for_each
  testing/scripts/tests/foreach
Labels: CI, bug, scripts
