Repository MRtrix3/mrtrix3, pull requests merged in 2020-05, with the labels that each got.

#2054 Math::Zstatistic: Fix compiler warning
  core/math/zstatistic.cpp
Labels: build

#2057 CohortDataImport::initialise(): Fix for cwd
  core/math/stats/import.h
Labels: bug

#2051 Add .gitattributes file
  .gitattributes
Labels: enhancement

#2062 dwifslpreproc: add missing reorient_fod option
  bin/dwifslpreproc
Labels: bug, scripts

#2061 progressbar: fix behaviour under redirection
  core/progressbar.cpp
  core/progressbar.h
Labels: bug
