Repository MRtrix3/mrtrix3, pull requests merged in 2020-01, with the labels that each got.

#1861 Header::create(): Don't read 4D schemes from cmdline options
  core/dwi/gradient.cpp
  core/dwi/gradient.h
  core/header.cpp
  core/phase_encoding.cpp
Labels: bug

#1872 dwifslpreproc: Additional docs RE: FSL command options
  bin/dwifslpreproc
  docs/dwi_preprocessing/dwifslpreproc.rst
  docs/reference/commands/dwifslpreproc.rst
Labels: documentation

#1876 mrview: fix view tool
  src/gui/mrview/adjust_button.h
  src/gui/mrview/tool/overlay.cpp
Labels: bug, gui

#1875 tckgen / tckedit: Ordered include regions
  cmd/tckgen.cpp
  docs/reference/commands/tckedit.rst
  docs/reference/commands/tckgen.rst
  src/dwi/tractography/editing/worker.cpp
  src/dwi/tractography/editing/worker.h
  src/dwi/tractography/properties.h
  src/dwi/tractography/roi.cpp
  src/dwi/tractography/roi.h
  src/dwi/tractography/tracking/exec.h
  src/dwi/tractography/tracking/tractography.cpp
  src/dwi/tractography/tracking/tractography.h
  testing/cmd/testing_unit_tests_ordered_include.cpp
  testing/cmd/testing_unit_tests_sh_precomputer.cpp
  testing/cmd/testing_unit_tests_to.cpp
  testing/src/unit_tests/tractography/roi_unit_tests.h
  testing/src/unit_tests/unit_test.h
  testing/tests/ordered_include
  testing/tests/sh_precomputer
  testing/tests/to
Labels: enhancement

#1379 New commands: mrcentroid, labelstats
  cmd/labelstats.cpp
  cmd/mrcentroid.cpp
  core/stats.cpp
  docs/reference/commands/labelstats.rst
  docs/reference/commands/mrcentroid.rst
  docs/reference/commands_list.rst
Labels: question

#1867 MRView: better filename elision in List Views
  src/gui/dialog/file.cpp
  src/gui/dialog/file.h
  src/gui/mrview/tool/base.h
  src/gui/mrview/tool/connectome/connectome.cpp
  src/gui/mrview/tool/fixel/fixel.cpp
  src/gui/mrview/tool/list_model_base.h
  src/gui/mrview/tool/odf/odf.cpp
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/screen_capture.cpp
  src/gui/mrview/tool/screen_capture.h
  src/gui/mrview/tool/tractography/track_scalar_file.cpp
  src/gui/mrview/tool/tractography/track_scalar_file.h
  src/gui/mrview/tool/tractography/tractography.cpp
  src/gui/mrview/tool/tractography/tractography.h
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
Labels: enhancement, gui

#1885 tractography: fix ROI construction when passed a 4D mask
  src/dwi/tractography/roi.cpp
Labels: bug

#1886 dwifslpreproc: Fix writing of matrix files for FSL
  bin/dwifslpreproc
Labels: bug, scripts

#1860 Macos native build workflow
  .github/workflows/checks.yml
  .github/workflows/package-macos-native.yml
  .github/workflows/package-windows-msys2.yml
Labels: CI, MacOSX, Windows, build

#1888 Formats::is_nifti(): Fix for images with short names
  core/formats/nifti_utils.h
Labels: bug

#1858 constrained least-squares: support non-zero constraints and equality constraints
  cmd/amp2response.cpp
  core/math/constrained_least_squares.h
  src/dwi/sdeconv/msmt_csd.h
  testing/cmd/testing_icls.cpp
  testing/tests/constrained_least_squares
Labels: enhancement

#1889 dwifslpreproc: Fix strides of images input to applytopup
  bin/dwifslpreproc
Labels: bug, scripts

#1887 dwifslpreproc: Use DWI shell clustering algorithm
  bin/dwifslpreproc
  cmd/mrinfo.cpp
  docs/reference/commands/mrinfo.rst
Labels: enhancement, scripts

#1890 fsl.check_first(): Disable cleanup on failure
  lib/mrtrix3/fsl.py
Labels: bug, scripts

#1892 matrix.save_numeric(): Fix for erroneous usage
  lib/mrtrix3/matrix.py
Labels: scripts

#1880 Mrview fix cursor jump mac os
  src/gui/mrview/mode/base.cpp
Labels: bug, gui

#1895 mrview: fix initial size of view tool
  src/gui/mrview/tool/base.cpp
  src/gui/mrview/tool/base.h
  src/gui/mrview/tool/connectome/connectome.cpp
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
Labels: enhancement, gui

#1894 mrview: add config option to show ortho view in a row
  docs/reference/config_file_options.rst
  src/gui/mrview/mode/ortho.cpp
  src/gui/mrview/mode/ortho.h
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/tool/view.h
  src/gui/mrview/window.cpp
Labels: enhancement, gui

#1891 Python: Better identification of string data
  lib/mrtrix3/app.py
  lib/mrtrix3/image.py
  lib/mrtrix3/matrix.py
  lib/mrtrix3/path.py
  lib/mrtrix3/phaseencoding.py
  lib/mrtrix3/run.py
  lib/mrtrix3/utils.py
Labels: scripts

#1898 run.command(): Keyword argument "env"
  lib/mrtrix3/run.py
Labels: enhancement, scripts

#1900 Python: Restore fix to ProgressBar line wrapping
  lib/mrtrix3/app.py
Labels: bug, scripts

#1903 mrtrix3.matrix: Precision changes
  bin/dwifslpreproc
  lib/mrtrix3/matrix.py
  lib/mrtrix3/phaseencoding.py
Labels: enhancement

#1908 5ttgen fsl: Check for unix "dc"
  lib/mrtrix3/_5ttgen/fsl.py
Labels: scripts

#1904 Python: No empty "command_history" outputs
  lib/mrtrix3/__init__.py
  lib/mrtrix3/matrix.py
  lib/mrtrix3/phaseencoding.py
  lib/mrtrix3/run.py
Labels: scripts

#1911 build: Don't remove bin/mrtrix3.pyc
  build
Labels: bug, build

#1910 Partially addressing Issue #1654
  .gitignore
  build
  check_syntax
  src/dwi/sdeconv/msmt_csd.h
Labels: CI

#1913 mrtrix3.algorithm: Fix for branch & version switch
  lib/mrtrix3/algorithm.py
Labels: bug, scripts

#1912 New config file option "BValueEpsilon"
  docs/reference/config_file_options.rst
  src/dwi/shells.cpp
  src/dwi/shells.h
Labels: enhancement

#1725 FEAT: New command connectomeedit
  cmd/connectomeedit.cpp
  docs/reference/commands/connectomeedit.rst
  docs/reference/commands_list.rst
  testing/tests/connectomeedit
Labels: scripts

#1918 run_pylint macOS head fix
  run_pylint
Labels: CI, MacOSX, bug

#1915 5ttcheck: Alter PVF check
  cmd/5ttcheck.cpp
  docs/reference/commands/5ttcheck.rst
Labels: enhancement

#1920 image.Header: Fix datatype() function
  lib/mrtrix3/image.py
Labels: bug, scripts

#1901 population_template: Keyvals of output data
  bin/population_template
Labels: bug, critical, scripts

#1902 population_template: Progress bars
  bin/population_template
  lib/mrtrix3/app.py
Labels: enhancement, scripts

#1916 population_template: remove relic str2filename conversion
  bin/population_template
Labels: bug

#1924 dwi2response msmt_5tt: Update for 5ttcheck changes
  lib/mrtrix3/dwi2response/msmt_5tt.py
Labels: bug, scripts

#1692 Run time improvements for nonlinear registration
  core/math/SH.h
  src/registration/transform/reorient.h
Labels: enhancement

#1923 image.statistics(): Return namedtuple
  bin/dwi2response
  bin/labelsgmfix
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
  lib/mrtrix3/image.py
Labels: scripts

#1927 Python API minor fixes
  lib/mrtrix3/app.py
  lib/mrtrix3/fsl.py
  lib/mrtrix3/run.py
Labels: scripts

#1926 Track files: Support multi-line key-values
  cmd/tckinfo.cpp
  src/dwi/tractography/file_base.cpp
  src/dwi/tractography/file_base.h
Labels: bug
