Repository MRtrix3/mrtrix3, pull requests merged in 2020-09, with the labels that each got.

#2151 dwi2response tournier: Use os.path.join()
  lib/mrtrix3/dwi2response/tournier.py
Labels: scripts

#2147 NIfTI2: Fix read following #1540
  core/file/nifti_utils.cpp
Labels: bug

#2150 dwifslpreproc: -topupfiles option
  bin/dwifslpreproc
  docs/reference/commands/dwifslpreproc.rst
Labels: enhancement, scripts

#2118 run_tests: allow different location for MRtrix executables
  .gitmodules
  run_tests
Labels: CI/tests

#2153 Docs: State Qt5 as GUI requirement
  docs/installation/build_from_source.rst
Labels: build, documentation, gui

#2159 mrgrid: ensure no oversampling when using nearest-neighbour interpolation
  core/filter/resize.h
Labels: bug, test wanted

#2162 Remove copy_ptr and fix handling of masks when more than 3D
  cmd/afdconnectivity.cpp
  cmd/dwi2tensor.cpp
  cmd/dwidenoise.cpp
  cmd/sh2peaks.cpp
Labels: bug

#2171 dwibiascorrect fsl: Revise warning
  lib/mrtrix3/dwibiascorrect/fsl.py
Labels: bug, documentation

#2170 Loop(): remove constructor from initializer_list
  core/algo/loop.h
Labels: enhancement

#2101 When building a -noshared configuration, statically link libgcc and libstdc++
  build
Labels: build, enhancement

#2166 dwifslpreproc: For EddyQC, don't invoke Python3 interpreter
  bin/dwifslpreproc
Labels: bug, scripts

#2178 convert_bruker: fix DW scheme handling
  bin/convert_bruker
Labels: bug

#2184 mrhistmatch: Use normal equation
  cmd/mrhistmatch.cpp
Labels: bug, critical

#2180 [BUG] tckgen: Fix absent CST with ACT
  core/interp/base.h
  core/interp/masked.h
  core/interp/sinc.h
  src/dwi/tractography/ACT/method.h
  src/dwi/tractography/algorithms/fact.h
  src/dwi/tractography/algorithms/iFOD1.h
  src/dwi/tractography/algorithms/iFOD2.h
  src/dwi/tractography/algorithms/nulldist.h
  src/dwi/tractography/algorithms/sd_stream.h
  src/dwi/tractography/algorithms/seedtest.h
  src/dwi/tractography/algorithms/tensor_det.h
  src/dwi/tractography/algorithms/tensor_prob.h
  src/dwi/tractography/tracking/exec.h
  src/dwi/tractography/tracking/method.h
  src/dwi/tractography/tracking/types.h
  testing/binaries/tests/tckgen
Labels: bug, critical

#2185 NIfTI: Fix verification of rigid transform
  core/file/nifti_utils.cpp
Labels: bug
