Repository MRtrix3/mrtrix3, pull requests merged in 2020-03, with the labels that each got.

#1963 JSON: Do not read / write "IntendedFor field
  core/file/json_utils.cpp
Labels: bug

#1965 Fix incorrect total readout time when parsing Siemens mosaics
  core/file/dicom/image.cpp
Labels: bug

#1969 mrmetric average space fix
  core/math/average_space.h
Labels: bug

#1948 Parrec
  core/formats/list.cpp
  core/formats/list.h
  core/formats/par.cpp
Labels: enhancement

#1970 5ttgen hsvs: Add missing LUT files
  share/mrtrix3/_5ttgen/hsvs/AmygSubfields.txt
  share/mrtrix3/_5ttgen/hsvs/HippSubfields.txt
Labels: scripts

#1968 matrix.save_numeric(): Fix enforcement of -force option
  bin/population_template
  bin/responsemean
  lib/mrtrix3/matrix.py
Labels: bug, scripts

#1972 dwinormalise warp fix
  lib/mrtrix3/dwinormalise/group.py
Labels: bug, scripts

#1974 Scripts terminal fixes
  bin/population_template
  lib/mrtrix3/run.py
Labels: scripts

#1978 Improved slice timing on Siemens
  core/file/dicom/mapper.cpp
Labels: bug, enhancement

#1933 Mrview transform tool
  configure
  core/file/dicom/image.cpp
  core/math/versor.h
  docs/reference/config_file_options.rst
  src/dwi/tractography/roi.cpp
  src/gui/dwi/render_frame.cpp
  src/gui/dwi/render_frame.h
  src/gui/mrview/gui_image.cpp
  src/gui/mrview/gui_image.h
  src/gui/mrview/mode/base.cpp
  src/gui/mrview/mode/base.h
  src/gui/mrview/mode/lightbox.cpp
  src/gui/mrview/mode/ortho.cpp
  src/gui/mrview/mode/volume.cpp
  src/gui/mrview/mode/volume.h
  src/gui/mrview/tool/base.cpp
  src/gui/mrview/tool/base.h
  src/gui/mrview/tool/connectome/edge.cpp
  src/gui/mrview/tool/list.h
  src/gui/mrview/tool/odf/odf.cpp
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/roi_editor/roi.h
  src/gui/mrview/tool/roi_editor/undoentry.cpp
  src/gui/mrview/tool/screen_capture.cpp
  src/gui/mrview/tool/screen_capture.h
  src/gui/mrview/tool/transform.cpp
  src/gui/mrview/tool/transform.h
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/tool/view.h
  src/gui/mrview/volume.cpp
  src/gui/mrview/volume.h
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
  src/gui/opengl/transformation.h
Labels: enhancement, gui

#1981 Fix configure qt error on msys2
  configure
Labels: bug, build

#1987 CI: Change mrregister test temp files
  testing/binaries/tests/mrregister
Labels: CI

#1932 fod2fixel: Revise options / help / code RE: "peaks"
  cmd/fod2fixel.cpp
  docs/reference/commands/fod2fixel.rst
  src/dwi/fmls.cpp
  src/dwi/fmls.h
Labels: question

#1990 dwifslpreproc merge fix
  bin/dwifslpreproc
Labels: bug, scripts

#1930 MRView ODF tool: add option to colour relative to projection
  src/gui/dwi/renderer.cpp
  src/gui/dwi/renderer.h
  src/gui/mrview/gui_image.h
  src/gui/mrview/tool/odf/odf.cpp
  src/gui/mrview/tool/odf/odf.h
Labels: enhancement, gui

#1994 dirmerge: Fix -unipolar_weight option
  cmd/dirmerge.cpp
  docs/reference/commands/dirmerge.rst
Labels: bug

#1995 DWI::Tractography::TrackScalar: Fix compilation on G++5
  cmd/tsfmult.cpp
  cmd/tsfsmooth.cpp
  cmd/tsfthreshold.cpp
  src/dwi/tractography/streamline.h
Labels: bug

#1999 DICOM: improve handling of time fields
  core/file/dicom/element.h
  core/file/dicom/image.cpp
Labels: enhancement
