Repository MRtrix3/mrtrix3, pull requests merged in 2020-07, with the labels that each got.

#2113 Support images with axis size greater than 2^31
  cmd/amp2response.cpp
  cmd/connectome2tck.cpp
  cmd/dwidenoise.cpp
  cmd/dwiextract.cpp
  cmd/maskfilter.cpp
  cmd/mrconvert.cpp
  cmd/mrdegibbs.cpp
  cmd/mredit.cpp
  cmd/mrfilter.cpp
  cmd/mrgrid.cpp
  cmd/mrregister.cpp
  cmd/mrtransform.cpp
  cmd/mtnormalise.cpp
  cmd/tckconvert.cpp
  cmd/tcksift.cpp
  cmd/tensor2metric.cpp
  core/adapter/extract.h
  core/adapter/median.h
  core/adapter/normalise3D.h
  core/adapter/reslice.cpp
  core/adapter/reslice.h
  core/app.h
  core/file/dicom/select_cmdline.cpp
  core/file/name_parser.cpp
  core/file/name_parser.h
  core/filter/fft.h
  core/filter/median.h
  core/filter/normalise.h
  core/filter/resize.h
  core/filter/reslice.h
  core/filter/smooth.h
  core/filter/warp.h
  core/formats/mrtrix_sparse_legacy.cpp
  core/formats/mrtrix_utils.h
  core/header.cpp
  core/mrtrix.cpp
  core/mrtrix.h
  core/stride.cpp
  src/dwi/sdeconv/csd.h
  src/dwi/sdeconv/msmt_csd.h
  src/dwi/tractography/SIFT/sifter.cpp
  src/dwi/tractography/SIFT/sifter.h
  src/gui/mrview/window.cpp
  src/registration/linear.cpp
  src/registration/linear.h
  src/registration/metric/local_cross_correlation.h
  src/registration/metric/params.h
  src/registration/multi_resolution_lmax.h
  src/registration/nonlinear.h
  src/registration/warp/compose.h
  testing/binaries/tests/mrconvert
  testing/cmd/testing_unit_tests_parse_ints.cpp
Labels: enhancement

#2109 Docs: Move fixel format to dedicated page in FBA
  docs/README.md
  docs/fixel_based_analysis/fixel_directory_format.rst
  docs/fixel_based_analysis/fixel_format.png
  docs/getting_started/image_data.rst
  docs/index.rst
Labels: documentation

#2127 dwifslpreproc: Fix eddy_quad susceptibility field
  bin/dwifslpreproc
Labels: bug, scripts

#2122 don't use QWheelEvent::pixelDelta() on Qt<5.5
  src/gui/dwi/render_frame.cpp
Labels: bug, critical, gui, test wanted

#2128 Fix matlab write mrtrix
  matlab/read_mrtrix.m
  matlab/write_mrtrix.m
Labels: bug, scripts

#2125 Pipe handler: ensure deletion of piped images even if not loaded
  cmd/mrinfo.cpp
  core/formats/pipe.cpp
  core/image_io/pipe.cpp
  core/image_io/pipe.h
  core/signal_handler.cpp
  core/signal_handler.h
  docs/getting_started/command_line.rst
  docs/reference/commands/mrinfo.rst
Labels: bug, critical, test wanted

#2132 dwi2fod: fix error when volumes not assigned to shells
  src/dwi/sdeconv/msmt_csd.h
Labels: bug, critical
