Repository MRtrix3/mrtrix3, pull requests merged in 2020-06, with the labels that each got.

#2067 dwifslpreproc: Don't discard modified dw_scheme
  bin/dwifslpreproc
Labels: bug, critical, scripts

#2070 mtnormalise: warn if only one contrast provided
  cmd/mtnormalise.cpp
Labels: enhancement

#2049 Updates to installation documentation
  .github/workflows/checks.yml
  .readthedocs.yml
  docs/README.md
  docs/conf.py
  docs/getting_started/image_data.rst
  docs/installation/build_from_source.rst
  docs/requirements.txt
Labels: documentation, enhancement

#2073 dwifslpreproc: eddy error message
  bin/dwifslpreproc
Labels: enhancement, scripts

#2080 Fix compiler warnings
  src/gui/dialog/dicom.cpp
  src/gui/dialog/file.cpp
  src/gui/dialog/list.cpp
  src/gui/dwi/render_frame.cpp
  src/gui/mrview/tool/connectome/matrix_list.h
  src/gui/mrview/tool/connectome/node_list.h
  src/gui/mrview/tool/odf/model.h
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/volume.cpp
  src/gui/mrview/window.cpp
Labels: CI, gui

#2093 fixelfilter: Remove erroneous DESCRIPTION statement
  cmd/fixelfilter.cpp
  docs/reference/commands/fixelfilter.rst
Labels: bug, documentation

#2060 Simplify gl_core header
  src/gui/opengl/gl_core_3_3.cpp
  src/gui/opengl/gl_core_3_3.h
Labels: build, gui

#2096 mrthreshold: Suppress progressbars if writing to cout
  cmd/mrthreshold.cpp
Labels: bug

#2100 run_tests: Permit running with manually-downloaded test data
  run_tests
Labels: CI/tests

#2076 Support FreeSurfer 7 LUT
  share/mrtrix3/labelconvert/fs2lobes_cinginc_convert.txt
  share/mrtrix3/labelconvert/fs2lobes_cingsep_convert.txt
  share/mrtrix3/labelconvert/fs_a2009s.txt
  share/mrtrix3/labelconvert/fs_default.txt
  src/gui/mrview/tool/connectome/connectome.cpp
Labels: bug, gui

#2068 mrview Tractography tool: Multiple fixes
  src/gui/mrview/tool/tractography/track_scalar_file.cpp
  src/gui/mrview/tool/tractography/tractogram.cpp
Labels: bug, gui

#2105 dwifslpreproc: Fix overwrite of output eddy_quad directory
  bin/dwifslpreproc
Labels: bug, scripts

#2094 write_mrtrix.m: Fix syntax
  matlab/write_mrtrix.m
Labels: bug

#2114 docs: replace mrresize by mrgrid
  cmd/mrconvert.cpp
  docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
  docs/fixel_based_analysis/st_fibre_density_cross-section.rst
  docs/quantitative_structural_connectivity/ismrm_hcp_tutorial.rst
  docs/reference/commands/mrconvert.rst
Labels: documentation
