Repository MRtrix3/mrtrix3, pull requests merged in 2020-02, with the labels that each got.

#1936 dwifslpreproc: Fix some error messages
  bin/dwifslpreproc
Labels: bug, scripts

#1931 Use thread local on macos
  src/dwi/tractography/algorithms/iFOD1.h
  src/dwi/tractography/algorithms/iFOD2.h
  src/dwi/tractography/algorithms/nulldist.h
  src/dwi/tractography/algorithms/tensor_prob.h
  src/dwi/tractography/rng.cpp
  src/dwi/tractography/rng.h
  src/dwi/tractography/seeding/basic.cpp
  src/dwi/tractography/seeding/dynamic.cpp
  src/dwi/tractography/seeding/gmwmi.cpp
  src/dwi/tractography/seeding/list.cpp
  src/dwi/tractography/tracking/exec.h
  src/dwi/tractography/tracking/method.cpp
Labels: MacOSX, enhancement

#1929 DICOM: allow simple selection of series from environment variables
  core/file/dicom/select_cmdline.cpp
  core/file/dicom/tree.cpp
  core/mrtrix.cpp
  core/mrtrix.h
  docs/reference/environment_variables.rst
Labels: enhancement

#1941 docs: add MRtrix3 paper and mention Unix tutorial
  docs/getting_started/beginner_dwi_tutorial.rst
  docs/getting_started/key_features.rst
  docs/installation/before_install.rst
Labels: documentation

#1943 dwi2response: Fixes for #1874
  cmd/fixel2peaks.cpp
  docs/reference/commands/fixel2peaks.rst
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
Labels: bug, scripts

#1949 mrview use comma as separator when copying focus position
  src/gui/mrview/tool/view.cpp
Labels: enhancement, gui

#1951 population_template: fix to mapping between mask and images
  bin/population_template
Labels: bug

#1954 configure: fix Makefile.release not found error
  configure
Labels: Windows, bug, build, critical

#1957 Script tweaks
  lib/mrtrix3/matrix.py
  lib/mrtrix3/phaseencoding.py
  lib/mrtrix3/run.py
Labels: scripts

#1945 fixel2voxel none: Revert default fill to 0.0
  cmd/fixel2voxel.cpp
  docs/reference/commands/fixel2voxel.rst
Labels: CI

#1937 dwifslpreproc: Changes to slice timing handling
  bin/dwifslpreproc
  core/file/dicom/mapper.cpp
Labels: bug, scripts

#1950 mrview: better handling of UTF-8 encodings
  src/gui/dialog/dicom.cpp
  src/gui/dialog/file.cpp
  src/gui/dialog/list.h
  src/gui/dialog/progress.cpp
  src/gui/dialog/report_exception.cpp
  src/gui/dwi/render_frame.cpp
  src/gui/gui.h
  src/gui/lighting_dock.cpp
  src/gui/mrview/colourmap_button.cpp
  src/gui/mrview/colourmap_menu.cpp
  src/gui/mrview/tool/connectome/file_data_vector.cpp
  src/gui/mrview/tool/connectome/file_data_vector.h
  src/gui/mrview/tool/connectome/matrix_list.h
  src/gui/mrview/tool/connectome/node_list.cpp
  src/gui/mrview/tool/connectome/selection.cpp
  src/gui/mrview/tool/fixel/base_fixel.h
  src/gui/mrview/tool/list_model_base.h
  src/gui/mrview/tool/odf/model.h
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/screen_capture.cpp
  src/gui/mrview/tool/tractography/track_scalar_file.cpp
  src/gui/mrview/tool/view.cpp
  src/gui/mrview/window.cpp
  src/gui/mrview/window.h
  src/gui/projection.h
  src/gui/shview/render_window.cpp
Labels: bug, gui

#1953 mrregister linear registration-related bugfixes
  cmd/mrregister.cpp
  core/math/average_space.cpp
  core/math/gradient_descent_bb.h
  src/registration/linear.cpp
  src/registration/linear.h
Labels: bug

#1959 CI renaming
  testing/binaries/tests/connectomeedit
  testing/cmd/testing_unit_tests_icls.cpp
  testing/tests/constrained_least_squares
  testing/tests/icls
Labels: CI
