Repository MRtrix3/mrtrix3, pull requests merged in 2021-05, with the labels that each got.

#2310 mrview: deactivate pan gesture to avoid #761
  src/gui/mrview/window.cpp
Labels: bug, gui

#2313 dwifslpreproc: Handle non-ascii data in eddy error outputs
  bin/dwifslpreproc
  core/formats/tiff.cpp
  core/image_io/tiff.cpp
Labels: bug, scripts

#2318 dwifslpreproc: Fix eddy text file outputs (again)
  bin/dwifslpreproc
Labels: bug, critical, scripts

#2316 New envvar MRTRIX_LOGLEVEL
  core/app.cpp
  docs/reference/environment_variables.rst
  lib/mrtrix3/app.py
  lib/mrtrix3/image.py
  lib/mrtrix3/run.py
Labels: bug, scripts
