Repository MRtrix3/mrtrix3, pull requests merged in 2021-07, with the labels that each got.

#2311 DICOM: simplify handling of parsing in context of multi-frame
  bin/dwifslpreproc
  bin/for_each
  bin/population_template
  core/app.cpp
  core/app.h
  core/file/dicom/image.cpp
  core/formats/pipe.cpp
  core/header.cpp
  core/image.h
  core/mrtrix.h
  testing/scripts/tests/for_each
Labels: bug

#2308 Attempted fixes to phase encoding handling
  core/file/json_utils.cpp
  core/file/nifti_utils.cpp
  core/file/nifti_utils.h
  core/header.cpp
  core/phase_encoding.cpp
  core/phase_encoding.h
Labels: bug

#2286 dwifslpreproc: Compatibility between image padding and EddyQC
  bin/dwifslpreproc
Labels: bug, scripts

#2346 DICOM improvements
  core/exception.h
  core/file/dicom/dict.cpp
  core/file/dicom/image.cpp
  core/file/dicom/image.h
  core/file/dicom/mapper.cpp
  core/file/dicom/patient.h
  core/file/dicom/series.h
  core/file/dicom/study.cpp
  core/file/dicom/study.h
  core/file/dicom/tree.h
  core/image_diff.h
  core/memory.h
Labels: bug

#2334 mrview: elide ODF file names
  src/gui/mrview/tool/odf/model.h
  src/gui/mrview/tool/odf/odf.cpp
Labels: enhancement, gui

#2298 mtnormalise: add resilience to non-finite values in mask
  cmd/mtnormalise.cpp
  docs/reference/commands/mtnormalise.rst
Labels: bug

#2352 mrview: fix volume index reset after image switch
  src/gui/mrview/tool/overlay.cpp
Labels: bug, gui

#2354 Fixes the overlay colour map inversion gui bug
  src/gui/mrview/colourmap_button.cpp
  src/gui/mrview/colourmap_button.h
  src/gui/mrview/tool/overlay.cpp
Labels: bug, gui
