Repository MRtrix3/mrtrix3, pull requests merged in 2021-03, with the labels that each got.

#2291 mrview: fix glitch in handling of clip plane selection
  src/gui/mrview/window.cpp
Labels: bug, gui

#2293 Fix help page for algorithm module
  lib/mrtrix3/app.py
Labels: bug, documentation, scripts

#2294 GLM: Fix all_stats() segfault
  core/math/stats/glm.cpp
Labels: bug
