Repository MRtrix3/mrtrix3, pull requests merged in 2021-11, with the labels that each got.

#2373 dwi2response manual: avoid checking and calculating a brain mask
  bin/dwi2response
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/fa.py
  lib/mrtrix3/dwi2response/manual.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
Labels: scripts

#2395 README.md: Add Twitter reference
  README.md
Labels: documentation

#2401 minimal set of changes to pass pylint 2.11.1 tests
  bin/blend
  bin/convert_bruker
  bin/dwicat
  bin/dwifslpreproc
  bin/dwigradcheck
  bin/dwishellmath
  bin/for_each
  bin/labelsgmfix
  bin/mrtrix_cleanup
  bin/population_template
  build
  configure
  lib/mrtrix3/_5ttgen/hsvs.py
  lib/mrtrix3/__init__.py
  lib/mrtrix3/app.py
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
  lib/mrtrix3/dwibiascorrect/ants.py
  lib/mrtrix3/image.py
  lib/mrtrix3/path.py
  lib/mrtrix3/phaseencoding.py
  lib/mrtrix3/run.py
  lib/mrtrix3/utils.py
  update_copyright
Labels: scripts, CI/tests

#2402 CONTRIBUTING.md: Revise text RE: target branch for docs changes
  CONTRIBUTING.md
Labels: documentation

#2406 dev update
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  README.md
  bin/blend
  bin/dwi2response
  bin/dwicat
  bin/dwifslpreproc
  build
  cmd/dwiextract.cpp
  configure
  docs/concepts/fixels_dixels.rst
  lib/mrtrix3/dwi2response/dhollander.py
  lib/mrtrix3/dwi2response/fa.py
  lib/mrtrix3/dwi2response/manual.py
  lib/mrtrix3/dwi2response/msmt_5tt.py
  lib/mrtrix3/dwi2response/tax.py
  lib/mrtrix3/dwi2response/tournier.py
  lib/mrtrix3/phaseencoding.py
  testing/scripts/tests/dwicat
  update_copyright
  update_dev_doc
Labels: scripts, CI/tests
