Repository MRtrix3/mrtrix3, pull requests merged in 2022-03, with the labels that each got.

#2445 configure: ignore CFLAGS & LDFLAGS from qmake
  configure
Labels: build

#2444 build: fix pylint warnings
  build
Labels: build

#2447 tcksift2: Fix fixel masking
  src/dwi/tractography/SIFT/model.h
  src/dwi/tractography/SIFT2/tckfactor.cpp
  testing/binaries/tests/tcksift2
Labels: bug

#2434 Math::Sinc: Fix validity assertions
  core/math/sinc.h
Labels: bug

#2454 connectomestats: Fix GLM mode selection
  cmd/connectomestats.cpp
Labels: bug

#2448 tcksift2: -output_debug to fixel directory format
  cmd/afdconnectivity.cpp
  cmd/tcksift.cpp
  cmd/tcksift2.cpp
  core/fixel/helpers.h
  docs/reference/commands/tcksift.rst
  docs/reference/commands/tcksift2.rst
  src/dwi/tractography/SIFT/model_base.h
  src/dwi/tractography/SIFT/output.h
  src/dwi/tractography/SIFT/sift.cpp
  src/dwi/tractography/SIFT/sifter.cpp
  src/dwi/tractography/SIFT/sifter.h
  src/dwi/tractography/SIFT2/tckfactor.cpp
  src/dwi/tractography/SIFT2/tckfactor.h
  testing/binaries/tests/tcksift
  testing/binaries/tests/tcksift2
Labels: enhancement

#2209 mrtrix3.utils.RunList: Pass kwargs to run.command()
  lib/mrtrix3/utils.py
Labels: bug, scripts
