Repository MRtrix3/mrtrix3, pull requests merged in 2022-08, with the labels that each got.

#2497 mrview connectome tool: fix display of nodes when a node is empty
  src/gui/mrview/tool/connectome/connectome.cpp
Labels: bug, gui

#2503 Correctly transform mask instead of last contrast
  bin/population_template
Labels: bug, scripts

#2508 mrtransform: DWI grad export on linear
  cmd/mrtransform.cpp
Labels: bug

#2507 Write separate std_dev for each variance group
  cmd/mrclusterstats.cpp
Labels: bug
