Repository MRtrix3/mrtrix3, pull requests merged in 2022-11, with the labels that each got.

#2522 matlab: Fix erroneous reference to non-existent "tracks" identifier
  matlab/write_mrtrix_tsf.m
Labels: bug, matlab

#2475 python library: tweak execute to work with VS Code #2472
  lib/mrtrix3/__init__.py
Labels: scripts, test wanted

#2505 dwifslpreproc: Refine slspec modification
  bin/dwifslpreproc
Labels: bug, scripts

#2471 population_template initialisation and drift correction fixes
  bin/population_template
  docs/reference/commands/population_template.rst
Labels: bug

#2525 configure: fix Qt parameter parsing for MacOS
  configure
Labels: gui, build, MacOSX, test wanted

#2370 Container recipe updates following 3.0.3 release
  Dockerfile
  Singularity
  docs/installation/using_containers.rst
Labels: bug, gui, container

#2367 mrview: improved error reporting in fixel plot tool
  src/gui/mrview/tool/fixel/fixel.cpp
Labels: gui
