Repository MRtrix3/mrtrix3, pull requests merged in 2023-01, with the labels that each got.

#2501 Connected components minsize
  cmd/maskfilter.cpp
  core/filter/connected_components.h
  docs/reference/commands/maskfilter.rst
Labels: enhancement

#2566 python library: tweak execute to work with VS Code #2472
  lib/mrtrix3/__init__.py
Labels: bug, scripts

#2569 mrview: change option name -orientationlabel to avoid conflict with -orientation
  docs/reference/commands/mrview.rst
  src/gui/mrview/window.cpp
Labels: bug, gui
