Repository MRtrix3/mrtrix3, pull requests merged in 2023-10, with the labels that each got.

#2727 ReadTheDocs: updates to fix render
  .readthedocs.yml
  docs/Makefile
  docs/conf.py
  docs/make.bat
  docs/requirements.txt
Labels: documentation

#2733 Fix typo in CMake presets file
  CMakePresets.json
Labels: bug

#2735 add support for python importlib to locate MRtrix3 python libraries
  bin/mrtrix3.py
Labels: bug, critical, python

#2734 Add CMake module for using sanitizers
  CMakeLists.txt
  cmake/ECMEnableSanitizers.cmake
Labels: build
