Repository MRtrix3/mrtrix3, pull requests merged in 2023-07, with the labels that each got.

#2667 mrview: fix tsf custom colour
  src/gui/mrview/colourmap_button.cpp
  src/gui/mrview/colourmap_button.h
  src/gui/mrview/colourmap_menu.cpp
  src/gui/mrview/colourmap_menu.h
  src/gui/mrview/displayable.h
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/tractography/track_scalar_file.cpp
  src/gui/mrview/tool/tractography/track_scalar_file.h
  src/gui/mrview/tool/tractography/tractogram.cpp
  src/gui/mrview/tool/tractography/tractogram.h
  src/gui/mrview/tool/tractography/tractography.cpp
Labels: bug, gui

#2680 Population_template: Terminal tweaks
  bin/population_template
  docs/reference/commands/population_template.rst
Labels: scripts, documentation

#2681 FOD FMLS: fix assertion failure in retrospective assignment
  src/dwi/fmls.cpp
Labels: bug

#2686 CI: Install Python / numpy via mingw64
  .github/workflows/checks.yml
Labels: Windows, CI/tests
