Repository MRtrix3/mrtrix3, pull requests merged in 2024-04, with the labels that each got.

#2578 IVIM fitting
  cmd/dwi2adc.cpp
  docs/reference/commands/dwi2adc.rst
  docs/reference/commands_list.rst
Labels: enhancement

#2873 Fix CI clang-tidy review action
  .github/workflows/clang-tidy.yml
Labels: CI/tests

#2875 Use LLVM linker on Linux if available
  CMakeLists.txt
  cmake/LinkerSetup.cmake
Labels: build

#2779 Fix buffer overflow in DWI bootstrapping
  src/dwi/bootstrap.h
Labels: bug

#2882 Docs: New page on MRView "lock to image axes"
  docs/concepts/mrview_lock_axes/lockoff_nointerp.gif
  docs/concepts/mrview_lock_axes/lockoff_withinterp.gif
  docs/concepts/mrview_lock_axes/lockon_nohighlight.gif
  docs/concepts/mrview_lock_axes/lockon_withhighlight.gif
  docs/concepts/mrview_lock_axes/mrview_lock_axes.rst
  docs/concepts/mrview_lock_axes/overlay.png
  docs/index.rst
Labels: gui, documentation

#2879 Don't use std::move for return values
  core/file/nifti_utils.cpp
  core/formats/mrtrix_gz.cpp
  core/formats/mrtrix_sparse_legacy.cpp
  core/formats/pipe.cpp
  core/formats/ram.cpp
  core/formats/xds.cpp
  core/image.h
Labels: code quality
