Repository MRtrix3/mrtrix3, pull requests merged in 2024-01, with the labels that each got.

#2777 Output error messages in CI checks
  .github/workflows/checks.yml
Labels: CI/tests

#2775 Fix memory leaks related to PNG handling
  core/file/png.cpp
  core/image_io/png.cpp
Labels: bug

#2761 Fix memory leak in mrdegibbs
  core/math/fft.h
Labels: bug

#2784 mrmath: Fix unfreed memory
  cmd/mrmath.cpp
  core/misc/voxel2vector.h
Labels: bug

#2787 Set C++ as the language in main CMakeLists.txt
  CMakeLists.txt
Labels: build

#2788 Fix clang-tidy config file path
  .github/workflows/clang-tidy.yml
Labels: CI/tests
