Repository MRtrix3/mrtrix3, pull requests merged in 2024-08, with the labels that each got.

#2957 Python API: Support Python 3.12
  python/mrtrix3/app.py
Labels: bug, critical, Python API

#2956 dwi2tensor: Update reference for constrained fit
  cmd/dwi2tensor.cpp
  docs/reference/commands/dwi2tensor.rst
Labels: documentation

#2950 Add interface library for project-wide compile options
  CMakeLists.txt
  cmd/CMakeLists.txt
  core/CMakeLists.txt
  core/file/npy.cpp
Labels: build, code quality

#2958 mrtrix3.run: Improved shebang parsing
  python/mrtrix3/run.py
Labels: Python API

#2859 Improve handling of external dependencies
  .github/workflows/checks.yml
  .github/workflows/clang-tidy.yml
  CMakeLists.txt
  cmake/Dependencies.cmake
  cmd/CMakeLists.txt
  cmd/mrinfo.cpp
  core/CMakeLists.txt
  core/file/json.h
  core/file/json_utils.h
  core/file/nifti_utils.cpp
  core/file/nifti_utils.h
  core/half.hpp
  thirdparty/nifti/nifti1.h
  thirdparty/nifti/nifti2.h
Labels: build

#2975 clang-format-all: Fix shebang
  clang-format-all
Labels: bug, code quality

#2886 Fix drag & drop on Windows for mrview
  src/gui/mrview/qthelpers.cpp
  src/gui/mrview/qthelpers.h
  src/gui/mrview/tool/fixel/fixel.cpp
  src/gui/mrview/tool/overlay.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/tractography/tractography.cpp
  src/gui/mrview/window.cpp
Labels: bug, gui, Windows

#2979 Download NifTI headers from remote host
  CMakeLists.txt
  cmake/Dependencies.cmake
  thirdparty/nifti/nifti1.h
  thirdparty/nifti/nifti2.h
Labels: build
