Repository MRtrix3/mrtrix3, pull requests merged in 2024-02, with the labels that each got.

#2805 Switch to Qt 6 as the default
  .github/workflows/checks.yml
  .github/workflows/clang-tidy.yml
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
Labels: build

#2817 Update sccache action to version 0.0.4
  .github/workflows/checks.yml
Labels: build, CI/tests

#2823 Script tests: add -force where necessary
  testing/scripts/tests/dwigradcheck
  testing/scripts/tests/for_each
Labels: bug, scripts, CI/tests

#2807 Add workflow to create tarball for Linux
  .github/workflows/package-linux-tarball.yml
  CMakeLists.txt
  install_mime_types.sh
  packaging/package-linux-tarball.sh
  share/CMakeLists.txt
  share/applications/mrview.desktop
  share/icons/hicolor/128x128/apps/application-x-mrtrix.png
  share/icons/hicolor/16x16/apps/application-x-mrtrix.png
  share/icons/hicolor/32x32/apps/application-x-mrtrix.png
  share/icons/hicolor/48x48/apps/application-x-mrtrix.png
  share/icons/hicolor/64x64/apps/application-x-mrtrix.png
  share/mime/mrtrix-mime.xml
Labels: build, CI/tests

#2700 Alter interface for registration robst linear estimator
  cmd/mrregister.cpp
  docs/reference/commands/population_template.rst
  python/bin/population_template
  src/registration/linear.cpp
Labels: help wanted
