Repository MRtrix3/mrtrix3, pull requests merged in 2024-06, with the labels that each got.

#2897 Fix compilation of big object files in MINGW debug builds
  CMakeLists.txt
Labels: bug, build, Windows

#2919 Add warning if cmake generator is not Ninja
  CMakeLists.txt
Labels: build

#2924 CMakeList.txt: fix very minor typo in warning message
  CMakeLists.txt
Labels: documentation

#2928 remove TIFF from build system following removal from code
  .github/workflows/checks.yml
  core/CMakeLists.txt
  packaging/mingw/PKGBUILD
  packaging/package-linux-tarball.sh
Labels: build

#2923 mrdegibbs: update doc to soften warning about partial Fourier
  cmd/mrdegibbs.cpp
  docs/reference/commands/mrdegibbs.rst
Labels: documentation

#2907 New option to build non-core code as a static lib
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build

#2932 Minor changes to packaging scripts
  packaging/macos/build
  packaging/mingw/PKGBUILD
  packaging/package-linux-tarball.sh
Labels: build

#2935 ProgressBar: Simple update method where stderr is pipe
  core/progressbar.cpp
Labels: bug
