Repository MRtrix3/mrtrix3, pull requests merged in 2024-03, with the labels that each got.

#2830 Merge packaging repos for MacOS and Windows
  packaging/macos/MRView.app/Contents/Info.plist
  packaging/macos/MRView.app/Contents/Resources/mrview.icns
  packaging/macos/MRView.app/Contents/Resources/mrview_doc.icns
  packaging/macos/MRView.app/Contents/lib
  packaging/macos/MRView.app/Contents/plugins
  packaging/macos/README.md
  packaging/macos/SHView.app/Contents/Info.plist
  packaging/macos/SHView.app/Contents/Resources
  packaging/macos/SHView.app/Contents/lib
  packaging/macos/SHView.app/Contents/plugins
  packaging/macos/build
  packaging/macos/install
  packaging/macos/mrview
  packaging/macos/shview
  packaging/macos/uninstall
  packaging/mingw/PKGBUILD
  packaging/mingw/README.md
  packaging/mingw/run.sh
Labels: build, Windows, MacOSX

#2840 Python API: Change citation notification
  python/lib/mrtrix3/app.py
Labels: Python API

#2834 Regenerate CMake tests when test file is modified
  cmake/BashTests.cmake
Labels: build, CI/tests

#2802 population_template: Fix linear drift correction
  python/bin/population_template
Labels: bug, scripts

#2843 Disable LTO in msys2 packaging script
  packaging/mingw/PKGBUILD
Labels: build, CI/tests

#2792 mrcat: Change positional argument structure
  cmd/mrcat.cpp
  docs/reference/commands/mrcat.rst
  testing/binaries/tests/mrcat
Labels: question

#2842 Fix the execution of NPY tests
  testing/tests/npy
  testing/tools/CMakeLists.txt
  testing/tools/testing_check_npy
  testing/tools/testing_gen_npy
  testing/tools/testing_npyread.cpp
  testing/tools/testing_npywrite.cpp
  testing/unit_tests/CMakeLists.txt
  testing/unit_tests/npyread
  testing/unit_tests/npywrite
Labels: build, CI/tests

#2833 mrregister: Fix erroneous reporting of default robust estimators
  docs/reference/commands/mrregister.rst
  src/registration/linear.cpp
Labels: documentation

#2851 Move share/mrtrix3/labelsgmfix to share/mrtrix3/labelsgmfirst
  share/mrtrix3/labelsgmfirst/FreeSurferSGM.txt
Labels: scripts

#2854 Update error message on version mismatch
  core/app.cpp
Labels: build

#2755 dev threading fixes
  core/algo/threaded_loop.h
  core/mutexprotected.h
  core/progressbar.h
Labels: bug

#2846 Fix python CLI CI test
  cmake/BashTests.cmake
  testing/data/python_cli/help.txt
  testing/unit_tests/CMakeLists.txt
  testing/unit_tests/cpp_cli
  testing/unit_tests/python_cli
Labels: CI/tests, Python API

#2863 Install MacOS CI packages using brew bundle
  .brewfile
  .github/workflows/checks.yml
Labels: MacOSX, CI/tests
