Repository MRtrix3/mrtrix3, pull requests merged in 2024-09, with the labels that each got.

#2981 5ttgen hsvs: Fix execution where FAST is not available
  python/mrtrix3/commands/5ttgen/hsvs.py
Labels: bug, scripts

#2983 dwibiasnormmask: Fix masking algorithm selection
  python/mrtrix3/commands/dwibiasnormmask.py
Labels: bug, scripts

#2982 Fix warnings from new pylint version
  python/mrtrix3/commands/dwi2mask/hdbet.py
  python/mrtrix3/commands/dwi2mask/mtnorm.py
  python/mrtrix3/commands/dwibiascorrect/mtnorm.py
  python/mrtrix3/commands/dwibiasnormmask.py
  python/mrtrix3/commands/dwigradcheck.py
  python/mrtrix3/commands/dwinormalise/mtnorm.py
  testing/pylint.rc
Labels: scripts, CI/tests

#2966 Python executables shebang: use env
  cmake/MakePythonExecutable.cmake
Labels: Python API

#2990 Disable download logs for NIfTI headers to the console
  cmake/Dependencies.cmake
Labels: build

#2992 responsemean: Fix terminal message for 1 b-value
  python/mrtrix3/commands/responsemean.py
Labels: bug, scripts

#2993 Download NIfTI headers from GitHub
  cmake/Dependencies.cmake
Labels: bug, build

#2989 Disable the use of LLD by default
  CMakeLists.txt
  cmake/LinkerSetup.cmake
Labels: build

#2997 Fix building project with non-git repos
  cmake/FindVersion.cmake
Labels: bug, build

#3008 dirrotate: Fix default test
  testing/binaries/tests/dirrotate/default
Labels: bug, CI/tests

#3006 Fix git version mismatch logic with shallow clones
  cmake/FindVersion.cmake
Labels: bug, build

#3004 Use FetchContent to download NIfTI headers
  cmake/Dependencies.cmake
Labels: bug, build

#2855 Update testing README
  testing/README.md
Labels: documentation, CI/tests
