Repository MRtrix3/mrtrix3, pull requests merged in 2024-05, with the labels that each got.

#2890 CI: Fixes for MacOSX ARM64 runner
  cmd/fod2fixel.cpp
  cmd/shbasis.cpp
  core/app.cpp
  src/dwi/directions/set.cpp
  testing/binaries/tests/dwidenoise
  testing/binaries/tests/mrcolour
  testing/binaries/tests/tckresample
  testing/binaries/tests/vectorstats
  testing/cmd/testing_diff_tck.cpp
Labels: help wanted, MacOSX, CI/tests

#2881 Disable LLD when using GCC with LTO enabled
  cmake/LinkerSetup.cmake
Labels: build

#2893 Master to dev
  .github/workflows/checks.yml
  .readthedocs.yml
  cmd/fod2fixel.cpp
  cmd/shbasis.cpp
  core/app.cpp
  core/file/dicom/element.cpp
  docs/Makefile
  docs/concepts/mrview_lock_axes/lockoff_nointerp.gif
  docs/concepts/mrview_lock_axes/lockoff_withinterp.gif
  docs/concepts/mrview_lock_axes/lockon_nohighlight.gif
  docs/concepts/mrview_lock_axes/lockon_withhighlight.gif
  docs/concepts/mrview_lock_axes/mrview_lock_axes.rst
  docs/concepts/mrview_lock_axes/overlay.png
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  matlab/write_mrtrix.m
  python/bin/5ttgen
  python/bin/blend
  python/bin/convert_bruker
  python/bin/dwi2response
  python/bin/dwibiascorrect
  python/bin/dwifslpreproc
  python/bin/dwigradcheck
  python/bin/dwinormalise
  python/bin/dwishellmath
  python/bin/for_each
  python/bin/gen_scheme
  python/bin/labelsgmfirst
  python/bin/mrtrix3.py
  python/bin/mrtrix_cleanup
  python/bin/notfound
  python/bin/population_template
  python/bin/responsemean
  src/dwi/directions/set.cpp
  testing/binaries/tests/dwidenoise
  testing/binaries/tests/mrcolour
  testing/binaries/tests/tckresample
  testing/binaries/tests/vectorstats
Labels: help wanted

#2889 Fix data race in ordered_queue tests
  testing/unit_tests/ordered_queue.cpp
Labels: bug, CI/tests

#2884 Add missing #define for mrview
  core/command.h
  src/gui/gui.h
Labels: bug, gui

#2880 Add new CMake target to build testing tools
  testing/tools/CMakeLists.txt
Labels: build

#2763 Add periodic checks with sanitizers
  .github/workflows/weekly_sanitizers.yml
Labels: CI/tests

#2899 dwifslpreproc: Fix -rpe_header with no phase encoding contrast
  python/bin/dwifslpreproc
Labels: bug, scripts

#2794 mrgrid: Fix help for -as option
  cmd/mrgrid.cpp
  docs/reference/commands/mrgrid.rst
Labels: documentation

#2803 run.command(): Do not hide list inputs
  lib/mrtrix3/run.py
Labels: Python API

#2721 for_each: Add example usage demonstrating shell operator escape
  bin/for_each
  docs/reference/commands/for_each.rst
Labels: scripts, documentation

#2698 mrinfo: Update author email
  cmd/mrinfo.cpp
  docs/reference/commands/mrinfo.rst
Labels: documentation

#2638 fod2fixel: Fix -fmls_lobe_merge_ratio
  src/dwi/fmls.cpp
Labels: bug

#2903 mrregister: Fix -nl_init option
  cmd/mrregister.cpp
Labels: bug

#2904 Update sanitizers workflow following testing changes
  .github/workflows/weekly_sanitizers.yml
Labels: CI/tests

#2914 OpenGL: Minimise what is imported by windows.h
  src/gui/opengl/gl_core_3_3.cpp
Labels: build, Windows, CI/tests

#2913 Add missing windows.h include header
  src/gui/opengl/gl_core_3_3.cpp
Labels: bug, build
