Repository MRtrix3/mrtrix3, pull requests merged in 2024-11, with the labels that each got.

#3030 Cancel previous Github Action runs in PRs
  .github/workflows/checks.yml
Labels: CI/tests

#2955 dwi2tensor: Preserve dw_scheme for -predicted_signal
  cmd/dwi2tensor.cpp
Labels: bug

#2908 DICOM command-line selection: abort on error reading from std::cin
  core/file/dicom/select_cmdline.cpp
Labels: bug, DICOM

#3001 population_template: Fix aggregation weights import
  bin/population_template
Labels: bug, scripts

#3005 Python: Pylint fix consider-using-generator
  bin/for_each
  bin/population_template
  bin/responsemean
  lib/mrtrix3/_5ttgen/hsvs.py
  lib/mrtrix3/fsl.py
  lib/mrtrix3/matrix.py
Labels: scripts, CI/tests, Python API

#2693 Docs: Fix missing boolean types in full usage
  core/app.cpp
Labels: bug, documentation

#2729 configure: strip FSL from PATH
  configure
Labels: build

#2559 Fix for mrview / singularity / NVIDIA
  docs/installation/using_containers.rst
Labels: bug, gui, documentation, container

#2929 Fixes to containers FSL dependency
  Dockerfile
  Singularity
Labels: bug, container
