Repository MRtrix3/mrtrix3, pull requests merged in 2025-05, with the labels that each got.

#3082 Remove misc-non-private-member-variables-in-classes check clang-tidy check
  .clang-tidy
Labels: code quality

#3097 Upgrade CMake version to 3.22 for MacOS CI
  .github/workflows/checks.yml
Labels: CI/tests

#3085 Correct C++ file paths for doxygen
  Doxyfile
Labels: documentation

#3095 tck2connectome: Fix erroneous assertion with -vector
  src/dwi/tractography/connectome/matrix.cpp
Labels: bug

#3102 Update clang-tidy-review action to 0.21.0
  .github/workflows/clang-tidy.yml
Labels: CI/tests

#3103 Derive MR::Exception from std::exception
  cpp/core/exception.cpp
  cpp/core/exception.h
Labels: code quality

#3081 Fixes for sanitisers workflow
  .github/workflows/weekly_sanitizers.yml
Labels: CI/tests
