Repository MRtrix3/mrtrix3, pull requests merged in 2025-03, with the labels that each got.

#3072 dwi2mask hdbet: Fix exception handling
  python/mrtrix3/commands/dwi2mask/hdbet.py
Labels: bug, scripts

#3076 5ttgen hsvs: Multiple changes / fixes
  docs/reference/commands/5ttgen.rst
  python/mrtrix3/commands/5ttgen/hsvs.py
Labels: bug, scripts, documentation

#3064 FIX: don't build gui subdirectory with BUILD_GUI=OFF
  cpp/CMakeLists.txt
Labels: bug, build

#3071 Fix tck writer when a single streamline exceed the buffer size
  src/dwi/tractography/file.h
Labels: bug

#3065 Update clang-tidy-review action to v0.20.1
  .github/workflows/clang-tidy.yml
Labels: build, CI/tests

#3077 dwi2tensor: Fix operation with -iter 1 (re-apply)
  cpp/cmd/dwi2tensor.cpp
  testing/CMakeLists.txt
Labels: bug, duplicate

#3057 5ttgen: Add Deep Atropos algorithm
  docs/reference/commands/5ttgen.rst
  python/mrtrix3/commands/5ttgen/__init__.py
  python/mrtrix3/commands/5ttgen/deep_atropos.py
  testing/CMakeLists.txt
  testing/scripts/CMakeLists.txt
  testing/scripts/tests/5ttgen/deepatropos_fromprob_default
  testing/scripts/tests/5ttgen/deepatropos_fromprob_whitestem
  testing/scripts/tests/5ttgen/deepatropos_fromseg_default
  testing/scripts/tests/5ttgen/deepatropos_fromseg_whitestem
Labels: scripts

#3052 Print build information at the end of configuration
  CMakeLists.txt
  cmake/BuildInfo.cmake
Labels: build

#3060 Include CMake modules in root CMakeLists.txt
  CMakeLists.txt
  cpp/CMakeLists.txt
Labels: build, CI/tests

#3069 Add individual targets for Python commands
  cpp/cmd/CMakeLists.txt
  python/mrtrix3/commands/CMakeLists.txt
Labels: build
