Repository MRtrix3/mrtrix3, pull requests merged in 2025-04, with the labels that each got.

#2609 fsl.check_first(): Second attempt at refinement
  bin/labelsgmfix
  lib/mrtrix3/_5ttgen/fsl.py
  lib/mrtrix3/_5ttgen/hsvs.py
  lib/mrtrix3/fsl.py
Labels: bug, scripts, test wanted

#2602 More robust bvecs/bvals compatibility
  bin/dwifslpreproc
  core/dwi/gradient.cpp
  core/dwi/gradient.h
  core/dwi/shells.h
Labels: bug, test wanted

#3089 Update sccache version to 0.0.9
  .github/workflows/checks.yml
  .github/workflows/weekly_sanitizers.yml
Labels: CI/tests

#3086 Fix packaging workflows on master
  .github/workflows/package-linux-anaconda.yml
  .github/workflows/package-macos-anaconda.yml
  .github/workflows/package-macos-native.yml
  .github/workflows/package-windows-msys2.yml
Labels: build, CI/tests
