Repository MRtrix3/mrtrix3, pull requests merged in 2025-10, with the labels that each got.

#2417 Increase BZeroThreshold
  cpp/core/dwi/gradient.cpp
  cpp/core/dwi/gradient.h
  docs/reference/config_file_options.rst
  python/mrtrix3/__init__.py
  python/mrtrix3/commands/dwi2response/dhollander.py
  python/mrtrix3/commands/dwicat.py
  python/mrtrix3/commands/dwifslpreproc.py
Labels: question

#2414 tckgen: New option -output_stats
  cpp/cmd/tckgen.cpp
  cpp/core/dwi/tractography/ACT/method.h
  cpp/core/dwi/tractography/algorithms/fact.h
  cpp/core/dwi/tractography/algorithms/iFOD1.h
  cpp/core/dwi/tractography/algorithms/iFOD2.h
  cpp/core/dwi/tractography/algorithms/nulldist.h
  cpp/core/dwi/tractography/algorithms/sd_stream.h
  cpp/core/dwi/tractography/algorithms/seedtest.h
  cpp/core/dwi/tractography/algorithms/tensor_det.h
  cpp/core/dwi/tractography/algorithms/tensor_prob.h
  cpp/core/dwi/tractography/roi.h
  cpp/core/dwi/tractography/seeding/seeding.cpp
  cpp/core/dwi/tractography/tracking/exec.h
  cpp/core/dwi/tractography/tracking/shared.cpp
  cpp/core/dwi/tractography/tracking/shared.h
  cpp/core/dwi/tractography/tracking/types.h
  cpp/core/dwi/tractography/tracking/write_kernel.h
  docs/reference/commands/tckgen.rst
  testing/binaries/CMakeLists.txt
  testing/binaries/tests/tckgen/output_stats
Labels: enhancement

#3203 Testing: Fix dirrotate default test
  testing/binaries/tests/dirrotate/default
Labels: CI/tests

#3207 Fix Eigen 3.4.1 type mismatch in `ColourMap` clamping
  src/colourmap.cpp
Labels: CI/tests

#3195 Fix ROI edits disappearing on MacOS
  src/gui/mrview/mode/slice.cpp
  src/gui/mrview/tool/roi_editor/item.cpp
  src/gui/mrview/tool/roi_editor/roi.cpp
  src/gui/mrview/tool/roi_editor/undoentry.cpp
Labels: bug, gui, MacOSX

#3205 tcksift2 & afdconnectivity: Update citation
  cmd/afdconnectivity.cpp
  cmd/tcksift2.cpp
  docs/reference/commands/afdconnectivity.rst
  docs/reference/commands/tcksift2.rst
Labels: documentation

#3050 tcksift2: Minor fixes to diagnosis data
  src/dwi/tractography/SIFT/output.h
  src/dwi/tractography/SIFT2/tckfactor.cpp
Labels: bug
