Repository MRtrix3/mrtrix3, pull requests merged in 2025-02, with the labels that each got.

#3042 Added info about consequences of using -white_stem in 5ttgen hsvs
  docs/reference/commands/5ttgen.rst
  lib/mrtrix3/_5ttgen/hsvs.py
Labels: documentation

#2722 dwifslpreproc: Fix for PE direction, but not readout time, in header
  bin/dwifslpreproc
  testing/scripts/tests/dwifslpreproc
Labels: bug, scripts

#2968 mrtrix3.path.wait_for(): Fix variable ghosting
  lib/mrtrix3/path.py
Labels: bug, Python API

#3049 voxel2mesh fixes
  cmd/voxel2mesh.cpp
  src/surface/algo/image2mesh.h
Labels: bug

#2767 DICOM: add null imageIO handler to allow parsing of DICOM data even with unsupported transfer syntax
  core/file/dicom/mapper.cpp
  core/image_io/null.cpp
  core/image_io/null.h
  docs/tips_and_tricks/dicom_handling.rst
Labels: enhancement, DICOM

#3027 Tolerance for dw_scheme differences on header merge
  cmd/dwiextract.cpp
  cmd/mrinfo.cpp
  cmd/mrtransform.cpp
  core/dwi/gradient.cpp
  core/dwi/gradient.h
  core/dwi/shells.h
  core/filter/dwi_brain_mask.h
  core/header.cpp
  src/dwi/sdeconv/csd.h
  testing/binaries/tests/mrcalc
Labels: bug

#3047 DICOM: ignore image positioning tags if nested within Philips private sequence
  core/file/dicom/image.cpp
Labels: bug, DICOM
